SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 创建核心业务数据库
CREATE DATABASE IF NOT EXISTS `gochat_user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `gochat_group` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `gochat_relation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `gochat_message` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
