// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"github.com/archyhsh/gochat/rpc/message/internal/logic"
	"github.com/archyhsh/gochat/rpc/message/internal/svc"
	"github.com/archyhsh/gochat/rpc/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) GetMessages(ctx context.Context, in *pb.GetMessagesRequest) (*pb.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}

func (s *MessageServiceServer) GetConversations(ctx context.Context, in *pb.GetConversationsRequest) (*pb.GetConversationsResponse, error) {
	l := logic.NewGetConversationsLogic(ctx, s.svcCtx)
	return l.GetConversations(in)
}

func (s *MessageServiceServer) ClearUnread(ctx context.Context, in *pb.ClearUnreadRequest) (*pb.ClearUnreadResponse, error) {
	l := logic.NewClearUnreadLogic(ctx, s.svcCtx)
	return l.ClearUnread(in)
}

func (s *MessageServiceServer) GetMessageByID(ctx context.Context, in *pb.GetMessageByIDRequest) (*pb.GetMessageByIDResponse, error) {
	l := logic.NewGetMessageByIDLogic(ctx, s.svcCtx)
	return l.GetMessageByID(in)
}
