// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	conversationFieldNames          = builder.RawFieldNames(&Conversation{})
	conversationRows                = strings.Join(conversationFieldNames, ",")
	conversationRowsExpectAutoSet   = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	conversationRowsWithPlaceHolder = strings.Join(stringx.Remove(conversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheConversationIdPrefix             = "cache:conversation:id:"
	cacheConversationConversationIdPrefix = "cache:conversation:conversationId:"
)

type (
	conversationModel interface {
		Insert(ctx context.Context, data *Conversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Conversation, error)
		FindOneByConversationId(ctx context.Context, conversationId string) (*Conversation, error)
		Update(ctx context.Context, data *Conversation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultConversationModel struct {
		sqlc.CachedConn
		table string
	}

	Conversation struct {
		Id             int64     `db:"id"`
		ConversationId string    `db:"conversation_id"`
		Type           int64     `db:"type"`      // type: 1private 2group
		TargetId       int64     `db:"target_id"` // user_id or group_id
		CreatedAt      time.Time `db:"created_at"`
	}
)

func newConversationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultConversationModel {
	return &defaultConversationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`conversation`",
	}
}

func (m *defaultConversationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	conversationConversationIdKey := fmt.Sprintf("%s%v", cacheConversationConversationIdPrefix, data.ConversationId)
	conversationIdKey := fmt.Sprintf("%s%v", cacheConversationIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, conversationConversationIdKey, conversationIdKey)
	return err
}

func (m *defaultConversationModel) FindOne(ctx context.Context, id int64) (*Conversation, error) {
	conversationIdKey := fmt.Sprintf("%s%v", cacheConversationIdPrefix, id)
	var resp Conversation
	err := m.QueryRowCtx(ctx, &resp, conversationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationModel) FindOneByConversationId(ctx context.Context, conversationId string) (*Conversation, error) {
	conversationConversationIdKey := fmt.Sprintf("%s%v", cacheConversationConversationIdPrefix, conversationId)
	var resp Conversation
	err := m.QueryRowIndexCtx(ctx, &resp, conversationConversationIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `conversation_id` = ? limit 1", conversationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, conversationId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultConversationModel) Insert(ctx context.Context, data *Conversation) (sql.Result, error) {
	conversationConversationIdKey := fmt.Sprintf("%s%v", cacheConversationConversationIdPrefix, data.ConversationId)
	conversationIdKey := fmt.Sprintf("%s%v", cacheConversationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, conversationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ConversationId, data.Type, data.TargetId)
	}, conversationConversationIdKey, conversationIdKey)
	return ret, err
}

func (m *defaultConversationModel) Update(ctx context.Context, newData *Conversation) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	conversationConversationIdKey := fmt.Sprintf("%s%v", cacheConversationConversationIdPrefix, data.ConversationId)
	conversationIdKey := fmt.Sprintf("%s%v", cacheConversationIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, conversationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ConversationId, newData.Type, newData.TargetId, newData.Id)
	}, conversationConversationIdKey, conversationIdKey)
	return err
}

func (m *defaultConversationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheConversationIdPrefix, primary)
}

func (m *defaultConversationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", conversationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultConversationModel) tableName() string {
	return m.table
}
