// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageTemplateFieldNames          = builder.RawFieldNames(&MessageTemplate{})
	messageTemplateRows                = strings.Join(messageTemplateFieldNames, ",")
	messageTemplateRowsExpectAutoSet   = strings.Join(stringx.Remove(messageTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageTemplateRowsWithPlaceHolder = strings.Join(stringx.Remove(messageTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMessageTemplateIdPrefix    = "cache:messageTemplate:id:"
	cacheMessageTemplateMsgIdPrefix = "cache:messageTemplate:msgId:"
)

type (
	messageTemplateModel interface {
		Insert(ctx context.Context, data *MessageTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MessageTemplate, error)
		FindOneByMsgId(ctx context.Context, msgId string) (*MessageTemplate, error)
		Update(ctx context.Context, data *MessageTemplate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMessageTemplateModel struct {
		sqlc.CachedConn
		table string
	}

	MessageTemplate struct {
		Id             int64          `db:"id"`
		MsgId          string         `db:"msg_id"`
		ConversationId string         `db:"conversation_id"`
		SenderId       int64          `db:"sender_id"`
		ReceiverId     int64          `db:"receiver_id"` // only for private chat
		GroupId        int64          `db:"group_id"`    // only for group chat
		MsgType        int64          `db:"msg_type"`    // type: 1text 2image 3file 4audio 5video 6system
		Content        sql.NullString `db:"content"`     // JSON format content
		Status         int64          `db:"status"`      // status: 0normal 1withdrawn
		CreatedAt      time.Time      `db:"created_at"`
	}
)

func newMessageTemplateModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageTemplateModel {
	return &defaultMessageTemplateModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message_template`",
	}
}

func (m *defaultMessageTemplateModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	messageTemplateIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateIdPrefix, id)
	messageTemplateMsgIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, messageTemplateIdKey, messageTemplateMsgIdKey)
	return err
}

func (m *defaultMessageTemplateModel) FindOne(ctx context.Context, id int64) (*MessageTemplate, error) {
	messageTemplateIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateIdPrefix, id)
	var resp MessageTemplate
	err := m.QueryRowCtx(ctx, &resp, messageTemplateIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageTemplateRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageTemplateModel) FindOneByMsgId(ctx context.Context, msgId string) (*MessageTemplate, error) {
	messageTemplateMsgIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateMsgIdPrefix, msgId)
	var resp MessageTemplate
	err := m.QueryRowIndexCtx(ctx, &resp, messageTemplateMsgIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `msg_id` = ? limit 1", messageTemplateRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, msgId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageTemplateModel) Insert(ctx context.Context, data *MessageTemplate) (sql.Result, error) {
	messageTemplateIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateIdPrefix, data.Id)
	messageTemplateMsgIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateMsgIdPrefix, data.MsgId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, messageTemplateRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MsgId, data.ConversationId, data.SenderId, data.ReceiverId, data.GroupId, data.MsgType, data.Content, data.Status)
	}, messageTemplateIdKey, messageTemplateMsgIdKey)
	return ret, err
}

func (m *defaultMessageTemplateModel) Update(ctx context.Context, newData *MessageTemplate) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	messageTemplateIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateIdPrefix, data.Id)
	messageTemplateMsgIdKey := fmt.Sprintf("%s%v", cacheMessageTemplateMsgIdPrefix, data.MsgId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageTemplateRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MsgId, newData.ConversationId, newData.SenderId, newData.ReceiverId, newData.GroupId, newData.MsgType, newData.Content, newData.Status, newData.Id)
	}, messageTemplateIdKey, messageTemplateMsgIdKey)
	return err
}

func (m *defaultMessageTemplateModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMessageTemplateIdPrefix, primary)
}

func (m *defaultMessageTemplateModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageTemplateRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageTemplateModel) tableName() string {
	return m.table
}
