// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageReadFieldNames          = builder.RawFieldNames(&MessageRead{})
	messageReadRows                = strings.Join(messageReadFieldNames, ",")
	messageReadRowsExpectAutoSet   = strings.Join(stringx.Remove(messageReadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageReadRowsWithPlaceHolder = strings.Join(stringx.Remove(messageReadFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMessageReadIdPrefix          = "cache:messageRead:id:"
	cacheMessageReadMsgIdUserIdPrefix = "cache:messageRead:msgId:userId:"
)

type (
	messageReadModel interface {
		Insert(ctx context.Context, data *MessageRead) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MessageRead, error)
		FindOneByMsgIdUserId(ctx context.Context, msgId string, userId int64) (*MessageRead, error)
		Update(ctx context.Context, data *MessageRead) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMessageReadModel struct {
		sqlc.CachedConn
		table string
	}

	MessageRead struct {
		Id     int64     `db:"id"`
		MsgId  string    `db:"msg_id"`
		UserId int64     `db:"user_id"`
		ReadAt time.Time `db:"read_at"`
	}
)

func newMessageReadModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageReadModel {
	return &defaultMessageReadModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message_read`",
	}
}

func (m *defaultMessageReadModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	messageReadIdKey := fmt.Sprintf("%s%v", cacheMessageReadIdPrefix, id)
	messageReadMsgIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMessageReadMsgIdUserIdPrefix, data.MsgId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, messageReadIdKey, messageReadMsgIdUserIdKey)
	return err
}

func (m *defaultMessageReadModel) FindOne(ctx context.Context, id int64) (*MessageRead, error) {
	messageReadIdKey := fmt.Sprintf("%s%v", cacheMessageReadIdPrefix, id)
	var resp MessageRead
	err := m.QueryRowCtx(ctx, &resp, messageReadIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageReadRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageReadModel) FindOneByMsgIdUserId(ctx context.Context, msgId string, userId int64) (*MessageRead, error) {
	messageReadMsgIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMessageReadMsgIdUserIdPrefix, msgId, userId)
	var resp MessageRead
	err := m.QueryRowIndexCtx(ctx, &resp, messageReadMsgIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `msg_id` = ? and `user_id` = ? limit 1", messageReadRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, msgId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageReadModel) Insert(ctx context.Context, data *MessageRead) (sql.Result, error) {
	messageReadIdKey := fmt.Sprintf("%s%v", cacheMessageReadIdPrefix, data.Id)
	messageReadMsgIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMessageReadMsgIdUserIdPrefix, data.MsgId, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, messageReadRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MsgId, data.UserId, data.ReadAt)
	}, messageReadIdKey, messageReadMsgIdUserIdKey)
	return ret, err
}

func (m *defaultMessageReadModel) Update(ctx context.Context, newData *MessageRead) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	messageReadIdKey := fmt.Sprintf("%s%v", cacheMessageReadIdPrefix, data.Id)
	messageReadMsgIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheMessageReadMsgIdUserIdPrefix, data.MsgId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageReadRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MsgId, newData.UserId, newData.ReadAt, newData.Id)
	}, messageReadIdKey, messageReadMsgIdUserIdKey)
	return err
}

func (m *defaultMessageReadModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMessageReadIdPrefix, primary)
}

func (m *defaultMessageReadModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageReadRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageReadModel) tableName() string {
	return m.table
}
