// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userConversationFieldNames          = builder.RawFieldNames(&UserConversation{})
	userConversationRows                = strings.Join(userConversationFieldNames, ",")
	userConversationRowsExpectAutoSet   = strings.Join(stringx.Remove(userConversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userConversationRowsWithPlaceHolder = strings.Join(stringx.Remove(userConversationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserConversationIdPrefix                   = "cache:userConversation:id:"
	cacheUserConversationUserIdConversationIdPrefix = "cache:userConversation:userId:conversationId:"
)

type (
	userConversationModel interface {
		Insert(ctx context.Context, data *UserConversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserConversation, error)
		FindOneByUserIdConversationId(ctx context.Context, userId int64, conversationId string) (*UserConversation, error)
		Update(ctx context.Context, data *UserConversation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserConversationModel struct {
		sqlc.CachedConn
		table string
	}

	UserConversation struct {
		Id             int64     `db:"id"`
		UserId         int64     `db:"user_id"`
		ConversationId string    `db:"conversation_id"`
		PeerId         int64     `db:"peer_id"`     // Receiver or Group ID
		PeerName       string    `db:"peer_name"`   // Redundant peer name for search
		PeerAvatar     string    `db:"peer_avatar"` // Redundant peer avatar
		UnreadCount    int64     `db:"unread_count"`
		LastMsgId      string    `db:"last_msg_id"`
		LastMsgTime    time.Time `db:"last_msg_time"`
		LastMsgContent string    `db:"last_msg_content"`
		LastMsgType    int64     `db:"last_msg_type"`
		LastSenderId   int64     `db:"last_sender_id"`
		ReadSequence   int64     `db:"read_sequence"` // last read msg sequence
		IsTop          int64     `db:"is_top"`
		IsMuted        int64     `db:"is_muted"`
		IsDeleted      int64     `db:"is_deleted"`
		Version        int64     `db:"version"` // delete/top/muted version(for multiple devices)
		CreatedAt      time.Time `db:"created_at"`
		UpdatedAt      time.Time `db:"updated_at"`
	}
)

func newUserConversationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserConversationModel {
	return &defaultUserConversationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_conversation`",
	}
}

func (m *defaultUserConversationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userConversationIdKey := fmt.Sprintf("%s%v", cacheUserConversationIdPrefix, id)
	userConversationUserIdConversationIdKey := fmt.Sprintf("%s%v:%v", cacheUserConversationUserIdConversationIdPrefix, data.UserId, data.ConversationId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userConversationIdKey, userConversationUserIdConversationIdKey)
	return err
}

func (m *defaultUserConversationModel) FindOne(ctx context.Context, id int64) (*UserConversation, error) {
	userConversationIdKey := fmt.Sprintf("%s%v", cacheUserConversationIdPrefix, id)
	var resp UserConversation
	err := m.QueryRowCtx(ctx, &resp, userConversationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userConversationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserConversationModel) FindOneByUserIdConversationId(ctx context.Context, userId int64, conversationId string) (*UserConversation, error) {
	userConversationUserIdConversationIdKey := fmt.Sprintf("%s%v:%v", cacheUserConversationUserIdConversationIdPrefix, userId, conversationId)
	var resp UserConversation
	err := m.QueryRowIndexCtx(ctx, &resp, userConversationUserIdConversationIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `conversation_id` = ? limit 1", userConversationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, conversationId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserConversationModel) Insert(ctx context.Context, data *UserConversation) (sql.Result, error) {
	userConversationIdKey := fmt.Sprintf("%s%v", cacheUserConversationIdPrefix, data.Id)
	userConversationUserIdConversationIdKey := fmt.Sprintf("%s%v:%v", cacheUserConversationUserIdConversationIdPrefix, data.UserId, data.ConversationId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userConversationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ConversationId, data.PeerId, data.PeerName, data.PeerAvatar, data.UnreadCount, data.LastMsgId, data.LastMsgTime, data.LastMsgContent, data.LastMsgType, data.LastSenderId, data.ReadSequence, data.IsTop, data.IsMuted, data.IsDeleted, data.Version)
	}, userConversationIdKey, userConversationUserIdConversationIdKey)
	return ret, err
}

func (m *defaultUserConversationModel) Update(ctx context.Context, newData *UserConversation) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userConversationIdKey := fmt.Sprintf("%s%v", cacheUserConversationIdPrefix, data.Id)
	userConversationUserIdConversationIdKey := fmt.Sprintf("%s%v:%v", cacheUserConversationUserIdConversationIdPrefix, data.UserId, data.ConversationId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userConversationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ConversationId, newData.PeerId, newData.PeerName, newData.PeerAvatar, newData.UnreadCount, newData.LastMsgId, newData.LastMsgTime, newData.LastMsgContent, newData.LastMsgType, newData.LastSenderId, newData.ReadSequence, newData.IsTop, newData.IsMuted, newData.IsDeleted, newData.Version, newData.Id)
	}, userConversationIdKey, userConversationUserIdConversationIdKey)
	return err
}

func (m *defaultUserConversationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserConversationIdPrefix, primary)
}

func (m *defaultUserConversationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userConversationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserConversationModel) tableName() string {
	return m.table
}
