// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyInfo struct {
	Id         int64  `json:"id"`
	FromUserId int64  `json:"from_user_id"`
	Message    string `json:"message"`
	Status     int    `json:"status"`
}

type ApplyListResponse struct {
	Applies []ApplyInfo `json:"applies"`
}

type ApplyRequest struct {
	ToUserId int64  `json:"to_user_id"`
	Message  string `json:"message,optional"`
}

type BlockFriendRequest struct {
	Id int64 `path:"id"`
}

type ClearUnreadRequest struct {
	ConversationId string `json:"conversation_id"`
}

type CommonResponse struct {
	Message string `json:"message"`
}

type Conversation struct {
	ConversationId  string `json:"conversation_id"`
	PeerId          int64  `json:"peer_id"`
	UnreadCount     int    `json:"unread_count"`
	LastMessage     string `json:"last_message"`
	LastMessageTime int64  `json:"last_message_time"`
}

type ConversationsResponse struct {
	Conversations []Conversation `json:"conversations"`
}

type CreateGroupRequest struct {
	Name        string `json:"name"`
	Avatar      string `json:"avatar,optional"`
	Description string `json:"description,optional"`
}

type DeleteFriendRequest struct {
	Id int64 `path:"id"`
}

type DismissGroupRequest struct {
	GroupId int64 `path:"id"`
}

type DispatchRequest struct {
	Service string `path:"service"`
	Action  string `path:"action"`
	Data    string `json:"data"` // JSON string of the real request
}

type DispatchResponse struct {
	Data string `json:"data"` // JSON string of the real response
}

type ForgotPasswordRequest struct {
	Username    string `json:"username"`
	NewPassword string `json:"new_password"`
}

type FriendInfo struct {
	UserId   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Remark   string `json:"remark"`
}

type FriendListResponse struct {
	Friends []FriendInfo `json:"friends"`
}

type GetAnnouncementRequest struct {
	Id int64 `path:"id"`
}

type GetGroupInfoRequest struct {
	GroupId int64 `path:"id"`
}

type GetGroupMembersRequest struct {
	GroupId int64 `path:"id"`
}

type GetMessageByIdRequest struct {
	MsgId string `path:"msg_id"`
}

type GetMessagesRequest struct {
	ConversationId string `form:"conversation_id"`
	Limit          int    `form:"limit,default=20"`
	LastSequence   int64  `form:"last_sequence,optional"`
}

type GetUserRequest struct {
	Id int64 `path:"id"`
}

type GroupInfo struct {
	GroupId      int64  `json:"id"`
	Name         string `json:"name"`
	Avatar       string `json:"avatar"`
	Description  string `json:"description"`
	Announcement string `json:"announcement"`
	OwnerId      int64  `json:"owner_id"`
}

type GroupListResponse struct {
	Groups []GroupInfo `json:"groups"`
}

type GroupMember struct {
	UserId   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int    `json:"role"`
}

type GroupMembersResponse struct {
	Members []GroupMember `json:"members"`
}

type HandleApplyRequest struct {
	ApplyId int64 `json:"apply_id"`
	Accept  bool  `json:"accept"`
}

type InviteRequest struct {
	Id        int64   `path:"id"`
	MemberIds []int64 `json:"member_ids"`
}

type JoinGroupRequest struct {
	GroupId int64  `path:"id"`
	Message string `json:"message,optional"`
}

type KickMemberRequest struct {
	GroupId  int64 `path:"id"`
	MemberId int64 `path:"member_id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type Message struct {
	MsgId          string `json:"msg_id"`
	ConversationId string `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	Content        string `json:"content"`
	MsgType        int    `json:"msg_type"`
	Timestamp      int64  `json:"timestamp"`
}

type MessagesResponse struct {
	Messages []Message `json:"messages"`
}

type PushRequest struct {
	UserIds         []int64 `json:"user_ids"`
	ConversationId  string  `json:"conversation_id"`
	MsgId           string  `json:"msg_id"`
	SenderId        int64   `json:"sender_id"`
	Content         string  `json:"content"`
	MsgType         int     `json:"msg_type"`
	Timestamp       int64   `json:"timestamp"`
	RelationVersion int64   `json:"relation_version,optional"`
}

type PushResponse struct {
	Success bool `json:"success"`
}

type QuitGroupRequest struct {
	GroupId int64 `path:"id"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RestoreConversationRequest struct {
	ConversationId string `json:"conversation_id"`
}

type SearchGroupsRequest struct {
	Keyword string `json:"keyword"`
}

type SearchRequest struct {
	Keyword string `form:"keyword"`
	Limit   int    `form:"limit,default=20"`
}

type SearchResponse struct {
	Users []User `json:"users"`
}

type SendMessageRequest struct {
	ConversationId string `json:"conversation_id"`
	Content        string `json:"content"`
	MsgType        int    `json:"msg_type"`
	ReceiverId     int64  `json:"receiver_id,optional"`
	GroupId        int64  `json:"group_id,optional"`
}

type SendMessageResponse struct {
	MsgId     string `json:"msg_id"`
	Timestamp int64  `json:"timestamp"`
}

type UnblockFriendRequest struct {
	Id int64 `path:"id"`
}

type UpdateAnnouncementRequest struct {
	Id      int64  `path:"id"`
	Content string `json:"content"`
}

type UpdateGroupNicknameRequest struct {
	GroupId  int64  `path:"id"`
	Nickname string `json:"nickname"`
}

type UpdateRemarkRequest struct {
	FriendId int64  `json:"friend_id"`
	Remark   string `json:"remark"`
}

type UpdateUserRequest struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Gender   int    `json:"gender,optional"`
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Gender   int    `json:"gender"`
}
