// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package relationservice

import (
	"context"

	"github.com/archyhsh/gochat/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyRequest          = pb.ApplyRequest
	ApplyResponse         = pb.ApplyResponse
	BlockFriendRequest    = pb.BlockFriendRequest
	BlockFriendResponse   = pb.BlockFriendResponse
	CheckFriendRequest    = pb.CheckFriendRequest
	CheckFriendResponse   = pb.CheckFriendResponse
	DeleteFriendRequest   = pb.DeleteFriendRequest
	DeleteFriendResponse  = pb.DeleteFriendResponse
	FriendApply           = pb.FriendApply
	GetApplyListRequest   = pb.GetApplyListRequest
	GetApplyListResponse  = pb.GetApplyListResponse
	GetFriendListRequest  = pb.GetFriendListRequest
	GetFriendListResponse = pb.GetFriendListResponse
	HandleApplyRequest    = pb.HandleApplyRequest
	HandleApplyResponse   = pb.HandleApplyResponse
	UnblockFriendRequest  = pb.UnblockFriendRequest
	UnblockFriendResponse = pb.UnblockFriendResponse
	UpdateRemarkRequest   = pb.UpdateRemarkRequest
	UpdateRemarkResponse  = pb.UpdateRemarkResponse

	RelationService interface {
		Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
		HandleApply(ctx context.Context, in *HandleApplyRequest, opts ...grpc.CallOption) (*HandleApplyResponse, error)
		GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error)
		GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
		BlockFriend(ctx context.Context, in *BlockFriendRequest, opts ...grpc.CallOption) (*BlockFriendResponse, error)
		UnblockFriend(ctx context.Context, in *UnblockFriendRequest, opts ...grpc.CallOption) (*UnblockFriendResponse, error)
		UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error)
		CheckFriend(ctx context.Context, in *CheckFriendRequest, opts ...grpc.CallOption) (*CheckFriendResponse, error)
	}

	defaultRelationService struct {
		cli zrpc.Client
	}
)

func NewRelationService(cli zrpc.Client) RelationService {
	return &defaultRelationService{
		cli: cli,
	}
}

func (m *defaultRelationService) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.Apply(ctx, in, opts...)
}

func (m *defaultRelationService) HandleApply(ctx context.Context, in *HandleApplyRequest, opts ...grpc.CallOption) (*HandleApplyResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.HandleApply(ctx, in, opts...)
}

func (m *defaultRelationService) GetFriendList(ctx context.Context, in *GetFriendListRequest, opts ...grpc.CallOption) (*GetFriendListResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.GetFriendList(ctx, in, opts...)
}

func (m *defaultRelationService) GetApplyList(ctx context.Context, in *GetApplyListRequest, opts ...grpc.CallOption) (*GetApplyListResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.GetApplyList(ctx, in, opts...)
}

func (m *defaultRelationService) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultRelationService) BlockFriend(ctx context.Context, in *BlockFriendRequest, opts ...grpc.CallOption) (*BlockFriendResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.BlockFriend(ctx, in, opts...)
}

func (m *defaultRelationService) UnblockFriend(ctx context.Context, in *UnblockFriendRequest, opts ...grpc.CallOption) (*UnblockFriendResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.UnblockFriend(ctx, in, opts...)
}

func (m *defaultRelationService) UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.UpdateRemark(ctx, in, opts...)
}

func (m *defaultRelationService) CheckFriend(ctx context.Context, in *CheckFriendRequest, opts ...grpc.CallOption) (*CheckFriendResponse, error) {
	client := pb.NewRelationServiceClient(m.cli.Conn())
	return client.CheckFriend(ctx, in, opts...)
}
