// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userDeviceFieldNames          = builder.RawFieldNames(&UserDevice{})
	userDeviceRows                = strings.Join(userDeviceFieldNames, ",")
	userDeviceRowsExpectAutoSet   = strings.Join(stringx.Remove(userDeviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userDeviceRowsWithPlaceHolder = strings.Join(stringx.Remove(userDeviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserDeviceIdPrefix             = "cache:userDevice:id:"
	cacheUserDeviceUserIdDeviceIdPrefix = "cache:userDevice:userId:deviceId:"
)

type (
	userDeviceModel interface {
		Insert(ctx context.Context, data *UserDevice) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserDevice, error)
		FindOneByUserIdDeviceId(ctx context.Context, userId int64, deviceId string) (*UserDevice, error)
		Update(ctx context.Context, data *UserDevice) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserDeviceModel struct {
		sqlc.CachedConn
		table string
	}

	UserDevice struct {
		Id           int64     `db:"id"`
		UserId       int64     `db:"user_id"`
		DeviceId     string    `db:"device_id"`
		Platform     string    `db:"platform"`
		PushToken    string    `db:"push_token"`
		LastActiveAt time.Time `db:"last_active_at"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newUserDeviceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserDeviceModel {
	return &defaultUserDeviceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_device`",
	}
}

func (m *defaultUserDeviceModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userDeviceIdKey := fmt.Sprintf("%s%v", cacheUserDeviceIdPrefix, id)
	userDeviceUserIdDeviceIdKey := fmt.Sprintf("%s%v:%v", cacheUserDeviceUserIdDeviceIdPrefix, data.UserId, data.DeviceId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userDeviceIdKey, userDeviceUserIdDeviceIdKey)
	return err
}

func (m *defaultUserDeviceModel) FindOne(ctx context.Context, id int64) (*UserDevice, error) {
	userDeviceIdKey := fmt.Sprintf("%s%v", cacheUserDeviceIdPrefix, id)
	var resp UserDevice
	err := m.QueryRowCtx(ctx, &resp, userDeviceIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDeviceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDeviceModel) FindOneByUserIdDeviceId(ctx context.Context, userId int64, deviceId string) (*UserDevice, error) {
	userDeviceUserIdDeviceIdKey := fmt.Sprintf("%s%v:%v", cacheUserDeviceUserIdDeviceIdPrefix, userId, deviceId)
	var resp UserDevice
	err := m.QueryRowIndexCtx(ctx, &resp, userDeviceUserIdDeviceIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `device_id` = ? limit 1", userDeviceRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, deviceId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDeviceModel) Insert(ctx context.Context, data *UserDevice) (sql.Result, error) {
	userDeviceIdKey := fmt.Sprintf("%s%v", cacheUserDeviceIdPrefix, data.Id)
	userDeviceUserIdDeviceIdKey := fmt.Sprintf("%s%v:%v", cacheUserDeviceUserIdDeviceIdPrefix, data.UserId, data.DeviceId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, userDeviceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.DeviceId, data.Platform, data.PushToken, data.LastActiveAt)
	}, userDeviceIdKey, userDeviceUserIdDeviceIdKey)
	return ret, err
}

func (m *defaultUserDeviceModel) Update(ctx context.Context, newData *UserDevice) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userDeviceIdKey := fmt.Sprintf("%s%v", cacheUserDeviceIdPrefix, data.Id)
	userDeviceUserIdDeviceIdKey := fmt.Sprintf("%s%v:%v", cacheUserDeviceUserIdDeviceIdPrefix, data.UserId, data.DeviceId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userDeviceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.DeviceId, newData.Platform, newData.PushToken, newData.LastActiveAt, newData.Id)
	}, userDeviceIdKey, userDeviceUserIdDeviceIdKey)
	return err
}

func (m *defaultUserDeviceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserDeviceIdPrefix, primary)
}

func (m *defaultUserDeviceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDeviceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserDeviceModel) tableName() string {
	return m.table
}
