// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	group "github.com/archyhsh/gochat/api/internal/handler/group"
	message "github.com/archyhsh/gochat/api/internal/handler/message"
	relation "github.com/archyhsh/gochat/api/internal/handler/relation"
	user "github.com/archyhsh/gochat/api/internal/handler/user"
	"github.com/archyhsh/gochat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/groups",
					Handler: group.CreateGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups",
					Handler: group.GetGroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups/:id",
					Handler: group.GetGroupInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/groups/:id",
					Handler: group.DismissGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/groups/:id/announcement",
					Handler: group.UpdateAnnouncementHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups/:id/announcement",
					Handler: group.GetAnnouncementHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/groups/:id/invite",
					Handler: group.InviteMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/groups/:id/join",
					Handler: group.JoinGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/groups/:id/kick/:member_id",
					Handler: group.KickMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups/:id/members",
					Handler: group.GetGroupMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/groups/:id/quit",
					Handler: group.QuitGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groups/search",
					Handler: group.SearchGroupsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/conversations",
					Handler: message.GetConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/conversations/clear_unread",
					Handler: message.ClearUnreadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/messages",
					Handler: message.GetMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/messages/:msg_id",
					Handler: message.GetMessageByIdHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/friend/apply",
					Handler: relation.ApplyFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/apply/handle",
					Handler: relation.HandleApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friend/apply/list",
					Handler: relation.GetApplyListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends",
					Handler: relation.GetFriendListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/friends/:id",
					Handler: relation.DeleteFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friends/:id/block",
					Handler: relation.BlockFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friends/:id/unblock",
					Handler: relation.UnblockFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/friends/remark",
					Handler: relation.UpdateRemarkHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/me",
					Handler: user.GetCurrentUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/me",
					Handler: user.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/search",
					Handler: user.SearchUsersHandler(serverCtx),
				},
			}...,
		),
	)
}
