// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendshipFieldNames          = builder.RawFieldNames(&Friendship{})
	friendshipRows                = strings.Join(friendshipFieldNames, ",")
	friendshipRowsExpectAutoSet   = strings.Join(stringx.Remove(friendshipFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendshipRowsWithPlaceHolder = strings.Join(stringx.Remove(friendshipFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendshipIdPrefix             = "cache:friendship:id:"
	cacheFriendshipUserIdFriendIdPrefix = "cache:friendship:userId:friendId:"
)

type (
	friendshipModel interface {
		Insert(ctx context.Context, data *Friendship) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friendship, error)
		FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*Friendship, error)
		Update(ctx context.Context, data *Friendship) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendshipModel struct {
		sqlc.CachedConn
		table string
	}

	Friendship struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"` // foreign key to user.id
		FriendId  int64     `db:"friend_id"`
		Remark    string    `db:"remark"`
		Status    int64     `db:"status"` // status: 0normal 1blacklisted
		Version   int64     `db:"version"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newFriendshipModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendshipModel {
	return &defaultFriendshipModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friendship`",
	}
}

func (m *defaultFriendshipModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendshipIdKey := fmt.Sprintf("%s%v", cacheFriendshipIdPrefix, id)
	friendshipUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendshipUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendshipIdKey, friendshipUserIdFriendIdKey)
	return err
}

func (m *defaultFriendshipModel) FindOne(ctx context.Context, id int64) (*Friendship, error) {
	friendshipIdKey := fmt.Sprintf("%s%v", cacheFriendshipIdPrefix, id)
	var resp Friendship
	err := m.QueryRowCtx(ctx, &resp, friendshipIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendshipRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendshipModel) FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*Friendship, error) {
	friendshipUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendshipUserIdFriendIdPrefix, userId, friendId)
	var resp Friendship
	err := m.QueryRowIndexCtx(ctx, &resp, friendshipUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", friendshipRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendshipModel) Insert(ctx context.Context, data *Friendship) (sql.Result, error) {
	friendshipIdKey := fmt.Sprintf("%s%v", cacheFriendshipIdPrefix, data.Id)
	friendshipUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendshipUserIdFriendIdPrefix, data.UserId, data.FriendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, friendshipRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Remark, data.Status, data.Version)
	}, friendshipIdKey, friendshipUserIdFriendIdKey)
	return ret, err
}

func (m *defaultFriendshipModel) Update(ctx context.Context, newData *Friendship) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendshipIdKey := fmt.Sprintf("%s%v", cacheFriendshipIdPrefix, data.Id)
	friendshipUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendshipUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendshipRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Remark, newData.Status, newData.Version, newData.Id)
	}, friendshipIdKey, friendshipUserIdFriendIdKey)
	return err
}

func (m *defaultFriendshipModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendshipIdPrefix, primary)
}

func (m *defaultFriendshipModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendshipRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendshipModel) tableName() string {
	return m.table
}
