// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendApplyFieldNames          = builder.RawFieldNames(&FriendApply{})
	friendApplyRows                = strings.Join(friendApplyFieldNames, ",")
	friendApplyRowsExpectAutoSet   = strings.Join(stringx.Remove(friendApplyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendApplyRowsWithPlaceHolder = strings.Join(stringx.Remove(friendApplyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendApplyIdPrefix = "cache:friendApply:id:"
)

type (
	friendApplyModel interface {
		Insert(ctx context.Context, data *FriendApply) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FriendApply, error)
		Update(ctx context.Context, data *FriendApply) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendApplyModel struct {
		sqlc.CachedConn
		table string
	}

	FriendApply struct {
		Id         int64     `db:"id"`
		FromUserId int64     `db:"from_user_id"`
		ToUserId   int64     `db:"to_user_id"`
		Message    string    `db:"message"`
		Status     int64     `db:"status"` // status: 0pending 1accepted 2rejected
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newFriendApplyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendApplyModel {
	return &defaultFriendApplyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_apply`",
	}
}

func (m *defaultFriendApplyModel) Delete(ctx context.Context, id int64) error {
	friendApplyIdKey := fmt.Sprintf("%s%v", cacheFriendApplyIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendApplyIdKey)
	return err
}

func (m *defaultFriendApplyModel) FindOne(ctx context.Context, id int64) (*FriendApply, error) {
	friendApplyIdKey := fmt.Sprintf("%s%v", cacheFriendApplyIdPrefix, id)
	var resp FriendApply
	err := m.QueryRowCtx(ctx, &resp, friendApplyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendApplyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendApplyModel) Insert(ctx context.Context, data *FriendApply) (sql.Result, error) {
	friendApplyIdKey := fmt.Sprintf("%s%v", cacheFriendApplyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, friendApplyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status)
	}, friendApplyIdKey)
	return ret, err
}

func (m *defaultFriendApplyModel) Update(ctx context.Context, data *FriendApply) error {
	friendApplyIdKey := fmt.Sprintf("%s%v", cacheFriendApplyIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendApplyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.Id)
	}, friendApplyIdKey)
	return err
}

func (m *defaultFriendApplyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendApplyIdPrefix, primary)
}

func (m *defaultFriendApplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendApplyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendApplyModel) tableName() string {
	return m.table
}
