// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package server

import (
	"context"

	"github.com/archyhsh/gochat/rpc/group/internal/logic"
	"github.com/archyhsh/gochat/rpc/group/internal/svc"
	"github.com/archyhsh/gochat/rpc/pb"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServiceServer) CreateGroup(ctx context.Context, in *pb.CreateGroupRequest) (*pb.CreateGroupResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServiceServer) GetGroupList(ctx context.Context, in *pb.GetGroupListRequest) (*pb.GetGroupListResponse, error) {
	l := logic.NewGetGroupListLogic(ctx, s.svcCtx)
	return l.GetGroupList(in)
}

func (s *GroupServiceServer) GetGroupInfo(ctx context.Context, in *pb.GetGroupInfoRequest) (*pb.GetGroupInfoResponse, error) {
	l := logic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

func (s *GroupServiceServer) GetGroupMembers(ctx context.Context, in *pb.GetGroupMembersRequest) (*pb.GetGroupMembersResponse, error) {
	l := logic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

func (s *GroupServiceServer) JoinGroup(ctx context.Context, in *pb.JoinGroupRequest) (*pb.JoinGroupResponse, error) {
	l := logic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *GroupServiceServer) QuitGroup(ctx context.Context, in *pb.QuitGroupRequest) (*pb.QuitGroupResponse, error) {
	l := logic.NewQuitGroupLogic(ctx, s.svcCtx)
	return l.QuitGroup(in)
}

func (s *GroupServiceServer) KickGroupMember(ctx context.Context, in *pb.KickGroupMemberRequest) (*pb.KickGroupMemberResponse, error) {
	l := logic.NewKickGroupMemberLogic(ctx, s.svcCtx)
	return l.KickGroupMember(in)
}

func (s *GroupServiceServer) DismissGroup(ctx context.Context, in *pb.DismissGroupRequest) (*pb.DismissGroupResponse, error) {
	l := logic.NewDismissGroupLogic(ctx, s.svcCtx)
	return l.DismissGroup(in)
}

func (s *GroupServiceServer) UpdateAnnouncement(ctx context.Context, in *pb.UpdateAnnouncementRequest) (*pb.UpdateAnnouncementResponse, error) {
	l := logic.NewUpdateAnnouncementLogic(ctx, s.svcCtx)
	return l.UpdateAnnouncement(in)
}

func (s *GroupServiceServer) GetAnnouncement(ctx context.Context, in *pb.GetAnnouncementRequest) (*pb.GetAnnouncementResponse, error) {
	l := logic.NewGetAnnouncementLogic(ctx, s.svcCtx)
	return l.GetAnnouncement(in)
}

func (s *GroupServiceServer) SearchGroups(ctx context.Context, in *pb.SearchGroupsRequest) (*pb.SearchGroupsResponse, error) {
	l := logic.NewSearchGroupsLogic(ctx, s.svcCtx)
	return l.SearchGroups(in)
}

func (s *GroupServiceServer) InviteMembers(ctx context.Context, in *pb.InviteMembersRequest) (*pb.InviteMembersResponse, error) {
	l := logic.NewInviteMembersLogic(ctx, s.svcCtx)
	return l.InviteMembers(in)
}

func (s *GroupServiceServer) CheckGroupMember(ctx context.Context, in *pb.CheckGroupMemberRequest) (*pb.CheckGroupMemberResponse, error) {
	l := logic.NewCheckGroupMemberLogic(ctx, s.svcCtx)
	return l.CheckGroupMember(in)
}

func (s *GroupServiceServer) UpdateGroupNickname(ctx context.Context, in *pb.UpdateGroupNicknameRequest) (*pb.UpdateGroupNicknameResponse, error) {
	l := logic.NewUpdateGroupNicknameLogic(ctx, s.svcCtx)
	return l.UpdateGroupNickname(in)
}
