// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupMemberFieldNames          = builder.RawFieldNames(&GroupMember{})
	groupMemberRows                = strings.Join(groupMemberFieldNames, ",")
	groupMemberRowsExpectAutoSet   = strings.Join(stringx.Remove(groupMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupMemberRowsWithPlaceHolder = strings.Join(stringx.Remove(groupMemberFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupMemberIdPrefix            = "cache:groupMember:id:"
	cacheGroupMemberGroupIdUserIdPrefix = "cache:groupMember:groupId:userId:"
)

type (
	groupMemberModel interface {
		Insert(ctx context.Context, data *GroupMember) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupMember, error)
		FindOneByGroupIdUserId(ctx context.Context, groupId int64, userId int64) (*GroupMember, error)
		Update(ctx context.Context, data *GroupMember) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupMemberModel struct {
		sqlc.CachedConn
		table string
	}

	GroupMember struct {
		Id          int64        `db:"id"`
		GroupId     int64        `db:"group_id"`
		UserId      int64        `db:"user_id"`
		Role        int64        `db:"role"`        // role: 0member 1adminstrator 2owner
		Nickname    string       `db:"nickname"`    // nickname in group
		MutedUntil  sql.NullTime `db:"muted_until"` // only before this time can send message, controlled by admin or owner
		JoinedAt    time.Time    `db:"joined_at"`
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"`
		InfoVersion int64        `db:"info_version"`
	}
)

func newGroupMemberModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupMemberModel {
	return &defaultGroupMemberModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`group_member`",
	}
}

func (m *defaultGroupMemberModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	groupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupMemberIdKey := fmt.Sprintf("%s%v", cacheGroupMemberIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, groupMemberGroupIdUserIdKey, groupMemberIdKey)
	return err
}

func (m *defaultGroupMemberModel) FindOne(ctx context.Context, id int64) (*GroupMember, error) {
	groupMemberIdKey := fmt.Sprintf("%s%v", cacheGroupMemberIdPrefix, id)
	var resp GroupMember
	err := m.QueryRowCtx(ctx, &resp, groupMemberIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupMemberRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMemberModel) FindOneByGroupIdUserId(ctx context.Context, groupId int64, userId int64) (*GroupMember, error) {
	groupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMemberGroupIdUserIdPrefix, groupId, userId)
	var resp GroupMember
	err := m.QueryRowIndexCtx(ctx, &resp, groupMemberGroupIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `group_id` = ? and `user_id` = ? limit 1", groupMemberRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, groupId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupMemberModel) Insert(ctx context.Context, data *GroupMember) (sql.Result, error) {
	groupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupMemberIdKey := fmt.Sprintf("%s%v", cacheGroupMemberIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, groupMemberRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.Role, data.Nickname, data.MutedUntil, data.JoinedAt, data.InfoVersion)
	}, groupMemberGroupIdUserIdKey, groupMemberIdKey)
	return ret, err
}

func (m *defaultGroupMemberModel) Update(ctx context.Context, newData *GroupMember) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	groupMemberGroupIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheGroupMemberGroupIdUserIdPrefix, data.GroupId, data.UserId)
	groupMemberIdKey := fmt.Sprintf("%s%v", cacheGroupMemberIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupMemberRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.GroupId, newData.UserId, newData.Role, newData.Nickname, newData.MutedUntil, newData.JoinedAt, newData.InfoVersion, newData.Id)
	}, groupMemberGroupIdUserIdKey, groupMemberIdKey)
	return err
}

func (m *defaultGroupMemberModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupMemberIdPrefix, primary)
}

func (m *defaultGroupMemberModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupMemberRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupMemberModel) tableName() string {
	return m.table
}
