// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupRequestFieldNames          = builder.RawFieldNames(&GroupRequest{})
	groupRequestRows                = strings.Join(groupRequestFieldNames, ",")
	groupRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(groupRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(groupRequestFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupRequestIdPrefix = "cache:groupRequest:id:"
)

type (
	groupRequestModel interface {
		Insert(ctx context.Context, data *GroupRequest) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupRequest, error)
		Update(ctx context.Context, data *GroupRequest) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupRequestModel struct {
		sqlc.CachedConn
		table string
	}

	GroupRequest struct {
		Id        int64     `db:"id"`
		GroupId   int64     `db:"group_id"`
		UserId    int64     `db:"user_id"`
		Message   string    `db:"message"` // application message
		Status    int64     `db:"status"`  // status: 0pending 1approved 2rejected
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newGroupRequestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupRequestModel {
	return &defaultGroupRequestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`group_request`",
	}
}

func (m *defaultGroupRequestModel) Delete(ctx context.Context, id int64) error {
	groupRequestIdKey := fmt.Sprintf("%s%v", cacheGroupRequestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, groupRequestIdKey)
	return err
}

func (m *defaultGroupRequestModel) FindOne(ctx context.Context, id int64) (*GroupRequest, error) {
	groupRequestIdKey := fmt.Sprintf("%s%v", cacheGroupRequestIdPrefix, id)
	var resp GroupRequest
	err := m.QueryRowCtx(ctx, &resp, groupRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupRequestModel) Insert(ctx context.Context, data *GroupRequest) (sql.Result, error) {
	groupRequestIdKey := fmt.Sprintf("%s%v", cacheGroupRequestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, groupRequestRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.Message, data.Status)
	}, groupRequestIdKey)
	return ret, err
}

func (m *defaultGroupRequestModel) Update(ctx context.Context, data *GroupRequest) error {
	groupRequestIdKey := fmt.Sprintf("%s%v", cacheGroupRequestIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupRequestRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.Message, data.Status, data.Id)
	}, groupRequestIdKey)
	return err
}

func (m *defaultGroupRequestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupRequestIdPrefix, primary)
}

func (m *defaultGroupRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupRequestModel) tableName() string {
	return m.table
}
