// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chat.proto

package chatservice

import (
	"context"

	"github.com/archyhsh/gochat/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AckPayload      = pb.AckPayload
	ErrorPayload    = pb.ErrorPayload
	IncomingMessage = pb.IncomingMessage
	KickRequest     = pb.KickRequest
	KickResponse    = pb.KickResponse
	OutgoingMessage = pb.OutgoingMessage
	PushRequest     = pb.PushRequest
	PushResponse    = pb.PushResponse
	ReadPayload     = pb.ReadPayload
	SystemPayload   = pb.SystemPayload
	TypingPayload   = pb.TypingPayload

	ChatService interface {
		StreamMessages(ctx context.Context, opts ...grpc.CallOption) (pb.ChatService_StreamMessagesClient, error)
		PushToUser(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
		KickUser(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

func (m *defaultChatService) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (pb.ChatService_StreamMessagesClient, error) {
	client := pb.NewChatServiceClient(m.cli.Conn())
	return client.StreamMessages(ctx, opts...)
}

func (m *defaultChatService) PushToUser(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	client := pb.NewChatServiceClient(m.cli.Conn())
	return client.PushToUser(ctx, in, opts...)
}

func (m *defaultChatService) KickUser(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error) {
	client := pb.NewChatServiceClient(m.cli.Conn())
	return client.KickUser(ctx, in, opts...)
}
