// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/archyhsh/gochat/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatMessage                 = pb.ChatMessage
	ChatMessageEvent            = pb.ChatMessageEvent
	ClearUnreadRequest          = pb.ClearUnreadRequest
	ClearUnreadResponse         = pb.ClearUnreadResponse
	ConversationInfo            = pb.ConversationInfo
	DeleteConversationRequest   = pb.DeleteConversationRequest
	DeleteConversationResponse  = pb.DeleteConversationResponse
	GetConversationsRequest     = pb.GetConversationsRequest
	GetConversationsResponse    = pb.GetConversationsResponse
	GetMessageByIDRequest       = pb.GetMessageByIDRequest
	GetMessageByIDResponse      = pb.GetMessageByIDResponse
	GetMessagesRequest          = pb.GetMessagesRequest
	GetMessagesResponse         = pb.GetMessagesResponse
	RestoreConversationRequest  = pb.RestoreConversationRequest
	RestoreConversationResponse = pb.RestoreConversationResponse
	SaveMessageRequest          = pb.SaveMessageRequest
	SaveMessageResponse         = pb.SaveMessageResponse

	MessageService interface {
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
		GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error)
		ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*ClearUnreadResponse, error)
		GetMessageByID(ctx context.Context, in *GetMessageByIDRequest, opts ...grpc.CallOption) (*GetMessageByIDResponse, error)
		SaveMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error)
		RestoreConversation(ctx context.Context, in *RestoreConversationRequest, opts ...grpc.CallOption) (*RestoreConversationResponse, error)
		DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

func (m *defaultMessageService) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

func (m *defaultMessageService) ClearUnread(ctx context.Context, in *ClearUnreadRequest, opts ...grpc.CallOption) (*ClearUnreadResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ClearUnread(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessageByID(ctx context.Context, in *GetMessageByIDRequest, opts ...grpc.CallOption) (*GetMessageByIDResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessageByID(ctx, in, opts...)
}

func (m *defaultMessageService) SaveMessage(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SaveMessage(ctx, in, opts...)
}

func (m *defaultMessageService) RestoreConversation(ctx context.Context, in *RestoreConversationRequest, opts ...grpc.CallOption) (*RestoreConversationResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.RestoreConversation(ctx, in, opts...)
}

func (m *defaultMessageService) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.DeleteConversation(ctx, in, opts...)
}
