// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: relation.proto

package server

import (
	"context"

	"github.com/archyhsh/gochat/rpc/pb"
	"github.com/archyhsh/gochat/rpc/relation/internal/logic"
	"github.com/archyhsh/gochat/rpc/relation/internal/svc"
)

type RelationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRelationServiceServer
}

func NewRelationServiceServer(svcCtx *svc.ServiceContext) *RelationServiceServer {
	return &RelationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServiceServer) Apply(ctx context.Context, in *pb.ApplyRequest) (*pb.ApplyResponse, error) {
	l := logic.NewApplyLogic(ctx, s.svcCtx)
	return l.Apply(in)
}

func (s *RelationServiceServer) HandleApply(ctx context.Context, in *pb.HandleApplyRequest) (*pb.HandleApplyResponse, error) {
	l := logic.NewHandleApplyLogic(ctx, s.svcCtx)
	return l.HandleApply(in)
}

func (s *RelationServiceServer) GetFriendList(ctx context.Context, in *pb.GetFriendListRequest) (*pb.GetFriendListResponse, error) {
	l := logic.NewGetFriendListLogic(ctx, s.svcCtx)
	return l.GetFriendList(in)
}

func (s *RelationServiceServer) GetApplyList(ctx context.Context, in *pb.GetApplyListRequest) (*pb.GetApplyListResponse, error) {
	l := logic.NewGetApplyListLogic(ctx, s.svcCtx)
	return l.GetApplyList(in)
}

func (s *RelationServiceServer) DeleteFriend(ctx context.Context, in *pb.DeleteFriendRequest) (*pb.DeleteFriendResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *RelationServiceServer) BlockFriend(ctx context.Context, in *pb.BlockFriendRequest) (*pb.BlockFriendResponse, error) {
	l := logic.NewBlockFriendLogic(ctx, s.svcCtx)
	return l.BlockFriend(in)
}

func (s *RelationServiceServer) UnblockFriend(ctx context.Context, in *pb.UnblockFriendRequest) (*pb.UnblockFriendResponse, error) {
	l := logic.NewUnblockFriendLogic(ctx, s.svcCtx)
	return l.UnblockFriend(in)
}

func (s *RelationServiceServer) UpdateRemark(ctx context.Context, in *pb.UpdateRemarkRequest) (*pb.UpdateRemarkResponse, error) {
	l := logic.NewUpdateRemarkLogic(ctx, s.svcCtx)
	return l.UpdateRemark(in)
}

func (s *RelationServiceServer) CheckFriend(ctx context.Context, in *pb.CheckFriendRequest) (*pb.CheckFriendResponse, error) {
	l := logic.NewCheckFriendLogic(ctx, s.svcCtx)
	return l.CheckFriend(in)
}
