// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package groupservice

import (
	"context"

	"github.com/archyhsh/gochat/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckGroupMemberRequest     = pb.CheckGroupMemberRequest
	CheckGroupMemberResponse    = pb.CheckGroupMemberResponse
	CreateGroupRequest          = pb.CreateGroupRequest
	CreateGroupResponse         = pb.CreateGroupResponse
	DismissGroupRequest         = pb.DismissGroupRequest
	DismissGroupResponse        = pb.DismissGroupResponse
	GetAnnouncementRequest      = pb.GetAnnouncementRequest
	GetAnnouncementResponse     = pb.GetAnnouncementResponse
	GetGroupInfoRequest         = pb.GetGroupInfoRequest
	GetGroupInfoResponse        = pb.GetGroupInfoResponse
	GetGroupListRequest         = pb.GetGroupListRequest
	GetGroupListResponse        = pb.GetGroupListResponse
	GetGroupMembersRequest      = pb.GetGroupMembersRequest
	GetGroupMembersResponse     = pb.GetGroupMembersResponse
	Group                       = pb.Group
	GroupMember                 = pb.GroupMember
	InviteMembersRequest        = pb.InviteMembersRequest
	InviteMembersResponse       = pb.InviteMembersResponse
	JoinGroupRequest            = pb.JoinGroupRequest
	JoinGroupResponse           = pb.JoinGroupResponse
	KickGroupMemberRequest      = pb.KickGroupMemberRequest
	KickGroupMemberResponse     = pb.KickGroupMemberResponse
	QuitGroupRequest            = pb.QuitGroupRequest
	QuitGroupResponse           = pb.QuitGroupResponse
	SearchGroupsRequest         = pb.SearchGroupsRequest
	SearchGroupsResponse        = pb.SearchGroupsResponse
	UpdateAnnouncementRequest   = pb.UpdateAnnouncementRequest
	UpdateAnnouncementResponse  = pb.UpdateAnnouncementResponse
	UpdateGroupNicknameRequest  = pb.UpdateGroupNicknameRequest
	UpdateGroupNicknameResponse = pb.UpdateGroupNicknameResponse

	GroupService interface {
		CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
		GetGroupList(ctx context.Context, in *GetGroupListRequest, opts ...grpc.CallOption) (*GetGroupListResponse, error)
		GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error)
		GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersResponse, error)
		JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error)
		QuitGroup(ctx context.Context, in *QuitGroupRequest, opts ...grpc.CallOption) (*QuitGroupResponse, error)
		KickGroupMember(ctx context.Context, in *KickGroupMemberRequest, opts ...grpc.CallOption) (*KickGroupMemberResponse, error)
		DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*DismissGroupResponse, error)
		UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...grpc.CallOption) (*UpdateAnnouncementResponse, error)
		GetAnnouncement(ctx context.Context, in *GetAnnouncementRequest, opts ...grpc.CallOption) (*GetAnnouncementResponse, error)
		SearchGroups(ctx context.Context, in *SearchGroupsRequest, opts ...grpc.CallOption) (*SearchGroupsResponse, error)
		InviteMembers(ctx context.Context, in *InviteMembersRequest, opts ...grpc.CallOption) (*InviteMembersResponse, error)
		CheckGroupMember(ctx context.Context, in *CheckGroupMemberRequest, opts ...grpc.CallOption) (*CheckGroupMemberResponse, error)
		UpdateGroupNickname(ctx context.Context, in *UpdateGroupNicknameRequest, opts ...grpc.CallOption) (*UpdateGroupNicknameResponse, error)
	}

	defaultGroupService struct {
		cli zrpc.Client
	}
)

func NewGroupService(cli zrpc.Client) GroupService {
	return &defaultGroupService{
		cli: cli,
	}
}

func (m *defaultGroupService) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroupService) GetGroupList(ctx context.Context, in *GetGroupListRequest, opts ...grpc.CallOption) (*GetGroupListResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.GetGroupList(ctx, in, opts...)
}

func (m *defaultGroupService) GetGroupInfo(ctx context.Context, in *GetGroupInfoRequest, opts ...grpc.CallOption) (*GetGroupInfoResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

func (m *defaultGroupService) GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}

func (m *defaultGroupService) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.JoinGroup(ctx, in, opts...)
}

func (m *defaultGroupService) QuitGroup(ctx context.Context, in *QuitGroupRequest, opts ...grpc.CallOption) (*QuitGroupResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.QuitGroup(ctx, in, opts...)
}

func (m *defaultGroupService) KickGroupMember(ctx context.Context, in *KickGroupMemberRequest, opts ...grpc.CallOption) (*KickGroupMemberResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.KickGroupMember(ctx, in, opts...)
}

func (m *defaultGroupService) DismissGroup(ctx context.Context, in *DismissGroupRequest, opts ...grpc.CallOption) (*DismissGroupResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.DismissGroup(ctx, in, opts...)
}

func (m *defaultGroupService) UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...grpc.CallOption) (*UpdateAnnouncementResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.UpdateAnnouncement(ctx, in, opts...)
}

func (m *defaultGroupService) GetAnnouncement(ctx context.Context, in *GetAnnouncementRequest, opts ...grpc.CallOption) (*GetAnnouncementResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.GetAnnouncement(ctx, in, opts...)
}

func (m *defaultGroupService) SearchGroups(ctx context.Context, in *SearchGroupsRequest, opts ...grpc.CallOption) (*SearchGroupsResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.SearchGroups(ctx, in, opts...)
}

func (m *defaultGroupService) InviteMembers(ctx context.Context, in *InviteMembersRequest, opts ...grpc.CallOption) (*InviteMembersResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.InviteMembers(ctx, in, opts...)
}

func (m *defaultGroupService) CheckGroupMember(ctx context.Context, in *CheckGroupMemberRequest, opts ...grpc.CallOption) (*CheckGroupMemberResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.CheckGroupMember(ctx, in, opts...)
}

func (m *defaultGroupService) UpdateGroupNickname(ctx context.Context, in *UpdateGroupNicknameRequest, opts ...grpc.CallOption) (*UpdateGroupNicknameResponse, error) {
	client := pb.NewGroupServiceClient(m.cli.Conn())
	return client.UpdateGroupNickname(ctx, in, opts...)
}
