// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: chat.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncomingMessage_Type int32

const (
	IncomingMessage_TYPE_UNSPECIFIED IncomingMessage_Type = 0
	IncomingMessage_TYPE_CHAT        IncomingMessage_Type = 1
	IncomingMessage_TYPE_ACK         IncomingMessage_Type = 2
	IncomingMessage_TYPE_READ        IncomingMessage_Type = 3
	IncomingMessage_TYPE_TYPING      IncomingMessage_Type = 4
	IncomingMessage_TYPE_HEARTBEAT   IncomingMessage_Type = 5
)

// Enum value maps for IncomingMessage_Type.
var (
	IncomingMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CHAT",
		2: "TYPE_ACK",
		3: "TYPE_READ",
		4: "TYPE_TYPING",
		5: "TYPE_HEARTBEAT",
	}
	IncomingMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CHAT":        1,
		"TYPE_ACK":         2,
		"TYPE_READ":        3,
		"TYPE_TYPING":      4,
		"TYPE_HEARTBEAT":   5,
	}
)

func (x IncomingMessage_Type) Enum() *IncomingMessage_Type {
	p := new(IncomingMessage_Type)
	*p = x
	return p
}

func (x IncomingMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncomingMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (IncomingMessage_Type) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x IncomingMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncomingMessage_Type.Descriptor instead.
func (IncomingMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0, 0}
}

type OutgoingMessage_Type int32

const (
	OutgoingMessage_TYPE_UNSPECIFIED OutgoingMessage_Type = 0
	OutgoingMessage_TYPE_CHAT        OutgoingMessage_Type = 1
	OutgoingMessage_TYPE_ACK         OutgoingMessage_Type = 2
	OutgoingMessage_TYPE_READ        OutgoingMessage_Type = 3
	OutgoingMessage_TYPE_TYPING      OutgoingMessage_Type = 4
	OutgoingMessage_TYPE_HEARTBEAT   OutgoingMessage_Type = 5
	OutgoingMessage_TYPE_ERROR       OutgoingMessage_Type = 6
	OutgoingMessage_TYPE_SYSTEM      OutgoingMessage_Type = 7
)

// Enum value maps for OutgoingMessage_Type.
var (
	OutgoingMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CHAT",
		2: "TYPE_ACK",
		3: "TYPE_READ",
		4: "TYPE_TYPING",
		5: "TYPE_HEARTBEAT",
		6: "TYPE_ERROR",
		7: "TYPE_SYSTEM",
	}
	OutgoingMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CHAT":        1,
		"TYPE_ACK":         2,
		"TYPE_READ":        3,
		"TYPE_TYPING":      4,
		"TYPE_HEARTBEAT":   5,
		"TYPE_ERROR":       6,
		"TYPE_SYSTEM":      7,
	}
)

func (x OutgoingMessage_Type) Enum() *OutgoingMessage_Type {
	p := new(OutgoingMessage_Type)
	*p = x
	return p
}

func (x OutgoingMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutgoingMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (OutgoingMessage_Type) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x OutgoingMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutgoingMessage_Type.Descriptor instead.
func (OutgoingMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1, 0}
}

type IncomingMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    IncomingMessage_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=gochat.rpc.IncomingMessage_Type" json:"type,omitempty"`
	TraceId string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IncomingMessage_ChatMsg
	//	*IncomingMessage_AckMsg
	//	*IncomingMessage_ReadMsg
	//	*IncomingMessage_TypingMsg
	Payload       isIncomingMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *IncomingMessage) GetType() IncomingMessage_Type {
	if x != nil {
		return x.Type
	}
	return IncomingMessage_TYPE_UNSPECIFIED
}

func (x *IncomingMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IncomingMessage) GetPayload() isIncomingMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IncomingMessage) GetChatMsg() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*IncomingMessage_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

func (x *IncomingMessage) GetAckMsg() *AckPayload {
	if x != nil {
		if x, ok := x.Payload.(*IncomingMessage_AckMsg); ok {
			return x.AckMsg
		}
	}
	return nil
}

func (x *IncomingMessage) GetReadMsg() *ReadPayload {
	if x != nil {
		if x, ok := x.Payload.(*IncomingMessage_ReadMsg); ok {
			return x.ReadMsg
		}
	}
	return nil
}

func (x *IncomingMessage) GetTypingMsg() *TypingPayload {
	if x != nil {
		if x, ok := x.Payload.(*IncomingMessage_TypingMsg); ok {
			return x.TypingMsg
		}
	}
	return nil
}

type isIncomingMessage_Payload interface {
	isIncomingMessage_Payload()
}

type IncomingMessage_ChatMsg struct {
	ChatMsg *ChatMessage `protobuf:"bytes,3,opt,name=chat_msg,json=chatMsg,proto3,oneof"`
}

type IncomingMessage_AckMsg struct {
	AckMsg *AckPayload `protobuf:"bytes,4,opt,name=ack_msg,json=ackMsg,proto3,oneof"`
}

type IncomingMessage_ReadMsg struct {
	ReadMsg *ReadPayload `protobuf:"bytes,5,opt,name=read_msg,json=readMsg,proto3,oneof"`
}

type IncomingMessage_TypingMsg struct {
	TypingMsg *TypingPayload `protobuf:"bytes,6,opt,name=typing_msg,json=typingMsg,proto3,oneof"`
}

func (*IncomingMessage_ChatMsg) isIncomingMessage_Payload() {}

func (*IncomingMessage_AckMsg) isIncomingMessage_Payload() {}

func (*IncomingMessage_ReadMsg) isIncomingMessage_Payload() {}

func (*IncomingMessage_TypingMsg) isIncomingMessage_Payload() {}

type OutgoingMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    OutgoingMessage_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=gochat.rpc.OutgoingMessage_Type" json:"type,omitempty"`
	TraceId string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OutgoingMessage_ChatMsg
	//	*OutgoingMessage_AckMsg
	//	*OutgoingMessage_ReadMsg
	//	*OutgoingMessage_TypingMsg
	//	*OutgoingMessage_ErrorMsg
	//	*OutgoingMessage_SystemMsg
	Payload       isOutgoingMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingMessage) Reset() {
	*x = OutgoingMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingMessage) ProtoMessage() {}

func (x *OutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingMessage.ProtoReflect.Descriptor instead.
func (*OutgoingMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *OutgoingMessage) GetType() OutgoingMessage_Type {
	if x != nil {
		return x.Type
	}
	return OutgoingMessage_TYPE_UNSPECIFIED
}

func (x *OutgoingMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OutgoingMessage) GetPayload() isOutgoingMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutgoingMessage) GetChatMsg() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

func (x *OutgoingMessage) GetAckMsg() *AckPayload {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_AckMsg); ok {
			return x.AckMsg
		}
	}
	return nil
}

func (x *OutgoingMessage) GetReadMsg() *ReadPayload {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_ReadMsg); ok {
			return x.ReadMsg
		}
	}
	return nil
}

func (x *OutgoingMessage) GetTypingMsg() *TypingPayload {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_TypingMsg); ok {
			return x.TypingMsg
		}
	}
	return nil
}

func (x *OutgoingMessage) GetErrorMsg() *ErrorPayload {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_ErrorMsg); ok {
			return x.ErrorMsg
		}
	}
	return nil
}

func (x *OutgoingMessage) GetSystemMsg() *SystemPayload {
	if x != nil {
		if x, ok := x.Payload.(*OutgoingMessage_SystemMsg); ok {
			return x.SystemMsg
		}
	}
	return nil
}

type isOutgoingMessage_Payload interface {
	isOutgoingMessage_Payload()
}

type OutgoingMessage_ChatMsg struct {
	ChatMsg *ChatMessage `protobuf:"bytes,3,opt,name=chat_msg,json=chatMsg,proto3,oneof"`
}

type OutgoingMessage_AckMsg struct {
	AckMsg *AckPayload `protobuf:"bytes,4,opt,name=ack_msg,json=ackMsg,proto3,oneof"`
}

type OutgoingMessage_ReadMsg struct {
	ReadMsg *ReadPayload `protobuf:"bytes,5,opt,name=read_msg,json=readMsg,proto3,oneof"`
}

type OutgoingMessage_TypingMsg struct {
	TypingMsg *TypingPayload `protobuf:"bytes,6,opt,name=typing_msg,json=typingMsg,proto3,oneof"`
}

type OutgoingMessage_ErrorMsg struct {
	ErrorMsg *ErrorPayload `protobuf:"bytes,7,opt,name=error_msg,json=errorMsg,proto3,oneof"`
}

type OutgoingMessage_SystemMsg struct {
	SystemMsg *SystemPayload `protobuf:"bytes,8,opt,name=system_msg,json=systemMsg,proto3,oneof"`
}

func (*OutgoingMessage_ChatMsg) isOutgoingMessage_Payload() {}

func (*OutgoingMessage_AckMsg) isOutgoingMessage_Payload() {}

func (*OutgoingMessage_ReadMsg) isOutgoingMessage_Payload() {}

func (*OutgoingMessage_TypingMsg) isOutgoingMessage_Payload() {}

func (*OutgoingMessage_ErrorMsg) isOutgoingMessage_Payload() {}

func (*OutgoingMessage_SystemMsg) isOutgoingMessage_Payload() {}

type AckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPayload) Reset() {
	*x = AckPayload{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPayload) ProtoMessage() {}

func (x *AckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPayload.ProtoReflect.Descriptor instead.
func (*AckPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *AckPayload) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *AckPayload) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReadPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MsgIds         []string               `protobuf:"bytes,2,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadPayload) Reset() {
	*x = ReadPayload{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPayload) ProtoMessage() {}

func (x *ReadPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPayload.ProtoReflect.Descriptor instead.
func (*ReadPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ReadPayload) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadPayload) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

type TypingPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	IsTyping       bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingPayload) Reset() {
	*x = TypingPayload{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingPayload) ProtoMessage() {}

func (x *TypingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingPayload.ProtoReflect.Descriptor instead.
func (*TypingPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *TypingPayload) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingPayload) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorPayload) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SystemPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemPayload) Reset() {
	*x = SystemPayload{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemPayload) ProtoMessage() {}

func (x *SystemPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemPayload.ProtoReflect.Descriptor instead.
func (*SystemPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *SystemPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemPayload) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       *OutgoingMessage       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *PushRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushRequest) GetMessage() *OutgoingMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PushResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type KickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *KickRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResponse) Reset() {
	*x = KickResponse{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponse) ProtoMessage() {}

func (x *KickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponse.ProtoReflect.Descriptor instead.
func (*KickResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *KickResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\n" +
	"gochat.rpc\x1a\fcommon.proto\x1a\rmessage.proto\"\xb7\x03\n" +
	"\x0fIncomingMessage\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .gochat.rpc.IncomingMessage.TypeR\x04type\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x124\n" +
	"\bchat_msg\x18\x03 \x01(\v2\x17.gochat.rpc.ChatMessageH\x00R\achatMsg\x121\n" +
	"\aack_msg\x18\x04 \x01(\v2\x16.gochat.rpc.AckPayloadH\x00R\x06ackMsg\x124\n" +
	"\bread_msg\x18\x05 \x01(\v2\x17.gochat.rpc.ReadPayloadH\x00R\areadMsg\x12:\n" +
	"\n" +
	"typing_msg\x18\x06 \x01(\v2\x19.gochat.rpc.TypingPayloadH\x00R\ttypingMsg\"m\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_CHAT\x10\x01\x12\f\n" +
	"\bTYPE_ACK\x10\x02\x12\r\n" +
	"\tTYPE_READ\x10\x03\x12\x0f\n" +
	"\vTYPE_TYPING\x10\x04\x12\x12\n" +
	"\x0eTYPE_HEARTBEAT\x10\x05B\t\n" +
	"\apayload\"\xce\x04\n" +
	"\x0fOutgoingMessage\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .gochat.rpc.OutgoingMessage.TypeR\x04type\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x124\n" +
	"\bchat_msg\x18\x03 \x01(\v2\x17.gochat.rpc.ChatMessageH\x00R\achatMsg\x121\n" +
	"\aack_msg\x18\x04 \x01(\v2\x16.gochat.rpc.AckPayloadH\x00R\x06ackMsg\x124\n" +
	"\bread_msg\x18\x05 \x01(\v2\x17.gochat.rpc.ReadPayloadH\x00R\areadMsg\x12:\n" +
	"\n" +
	"typing_msg\x18\x06 \x01(\v2\x19.gochat.rpc.TypingPayloadH\x00R\ttypingMsg\x127\n" +
	"\terror_msg\x18\a \x01(\v2\x18.gochat.rpc.ErrorPayloadH\x00R\berrorMsg\x12:\n" +
	"\n" +
	"system_msg\x18\b \x01(\v2\x19.gochat.rpc.SystemPayloadH\x00R\tsystemMsg\"\x8e\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_CHAT\x10\x01\x12\f\n" +
	"\bTYPE_ACK\x10\x02\x12\r\n" +
	"\tTYPE_READ\x10\x03\x12\x0f\n" +
	"\vTYPE_TYPING\x10\x04\x12\x12\n" +
	"\x0eTYPE_HEARTBEAT\x10\x05\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x06\x12\x0f\n" +
	"\vTYPE_SYSTEM\x10\aB\t\n" +
	"\apayload\";\n" +
	"\n" +
	"AckPayload\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"O\n" +
	"\vReadPayload\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\amsg_ids\x18\x02 \x03(\tR\x06msgIds\"U\n" +
	"\rTypingPayload\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\"<\n" +
	"\fErrorPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\rSystemPayload\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12:\n" +
	"\x05extra\x18\x02 \x03(\v2$.gochat.rpc.SystemPayload.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\vPushRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x125\n" +
	"\amessage\x18\x02 \x01(\v2\x1b.gochat.rpc.OutgoingMessageR\amessage\"<\n" +
	"\fPushResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\">\n" +
	"\vKickRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"<\n" +
	"\fKickResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base2\xdd\x01\n" +
	"\vChatService\x12N\n" +
	"\x0eStreamMessages\x12\x1b.gochat.rpc.IncomingMessage\x1a\x1b.gochat.rpc.OutgoingMessage(\x010\x01\x12?\n" +
	"\n" +
	"PushToUser\x12\x17.gochat.rpc.PushRequest\x1a\x18.gochat.rpc.PushResponse\x12=\n" +
	"\bKickUser\x12\x17.gochat.rpc.KickRequest\x1a\x18.gochat.rpc.KickResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chat_proto_goTypes = []any{
	(IncomingMessage_Type)(0), // 0: gochat.rpc.IncomingMessage.Type
	(OutgoingMessage_Type)(0), // 1: gochat.rpc.OutgoingMessage.Type
	(*IncomingMessage)(nil),   // 2: gochat.rpc.IncomingMessage
	(*OutgoingMessage)(nil),   // 3: gochat.rpc.OutgoingMessage
	(*AckPayload)(nil),        // 4: gochat.rpc.AckPayload
	(*ReadPayload)(nil),       // 5: gochat.rpc.ReadPayload
	(*TypingPayload)(nil),     // 6: gochat.rpc.TypingPayload
	(*ErrorPayload)(nil),      // 7: gochat.rpc.ErrorPayload
	(*SystemPayload)(nil),     // 8: gochat.rpc.SystemPayload
	(*PushRequest)(nil),       // 9: gochat.rpc.PushRequest
	(*PushResponse)(nil),      // 10: gochat.rpc.PushResponse
	(*KickRequest)(nil),       // 11: gochat.rpc.KickRequest
	(*KickResponse)(nil),      // 12: gochat.rpc.KickResponse
	nil,                       // 13: gochat.rpc.SystemPayload.ExtraEntry
	(*ChatMessage)(nil),       // 14: gochat.rpc.ChatMessage
	(*BaseResponse)(nil),      // 15: gochat.rpc.BaseResponse
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: gochat.rpc.IncomingMessage.type:type_name -> gochat.rpc.IncomingMessage.Type
	14, // 1: gochat.rpc.IncomingMessage.chat_msg:type_name -> gochat.rpc.ChatMessage
	4,  // 2: gochat.rpc.IncomingMessage.ack_msg:type_name -> gochat.rpc.AckPayload
	5,  // 3: gochat.rpc.IncomingMessage.read_msg:type_name -> gochat.rpc.ReadPayload
	6,  // 4: gochat.rpc.IncomingMessage.typing_msg:type_name -> gochat.rpc.TypingPayload
	1,  // 5: gochat.rpc.OutgoingMessage.type:type_name -> gochat.rpc.OutgoingMessage.Type
	14, // 6: gochat.rpc.OutgoingMessage.chat_msg:type_name -> gochat.rpc.ChatMessage
	4,  // 7: gochat.rpc.OutgoingMessage.ack_msg:type_name -> gochat.rpc.AckPayload
	5,  // 8: gochat.rpc.OutgoingMessage.read_msg:type_name -> gochat.rpc.ReadPayload
	6,  // 9: gochat.rpc.OutgoingMessage.typing_msg:type_name -> gochat.rpc.TypingPayload
	7,  // 10: gochat.rpc.OutgoingMessage.error_msg:type_name -> gochat.rpc.ErrorPayload
	8,  // 11: gochat.rpc.OutgoingMessage.system_msg:type_name -> gochat.rpc.SystemPayload
	13, // 12: gochat.rpc.SystemPayload.extra:type_name -> gochat.rpc.SystemPayload.ExtraEntry
	3,  // 13: gochat.rpc.PushRequest.message:type_name -> gochat.rpc.OutgoingMessage
	15, // 14: gochat.rpc.PushResponse.base:type_name -> gochat.rpc.BaseResponse
	15, // 15: gochat.rpc.KickResponse.base:type_name -> gochat.rpc.BaseResponse
	2,  // 16: gochat.rpc.ChatService.StreamMessages:input_type -> gochat.rpc.IncomingMessage
	9,  // 17: gochat.rpc.ChatService.PushToUser:input_type -> gochat.rpc.PushRequest
	11, // 18: gochat.rpc.ChatService.KickUser:input_type -> gochat.rpc.KickRequest
	3,  // 19: gochat.rpc.ChatService.StreamMessages:output_type -> gochat.rpc.OutgoingMessage
	10, // 20: gochat.rpc.ChatService.PushToUser:output_type -> gochat.rpc.PushResponse
	12, // 21: gochat.rpc.ChatService.KickUser:output_type -> gochat.rpc.KickResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_common_proto_init()
	file_message_proto_init()
	file_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*IncomingMessage_ChatMsg)(nil),
		(*IncomingMessage_AckMsg)(nil),
		(*IncomingMessage_ReadMsg)(nil),
		(*IncomingMessage_TypingMsg)(nil),
	}
	file_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*OutgoingMessage_ChatMsg)(nil),
		(*OutgoingMessage_AckMsg)(nil),
		(*OutgoingMessage_ReadMsg)(nil),
		(*OutgoingMessage_TypingMsg)(nil),
		(*OutgoingMessage_ErrorMsg)(nil),
		(*OutgoingMessage_SystemMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
