// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePlatform int32

const (
	DevicePlatform_PLATFORM_UNSPECIFIED DevicePlatform = 0
	DevicePlatform_PLATFORM_WEB         DevicePlatform = 1
	DevicePlatform_PLATFORM_IOS         DevicePlatform = 2
	DevicePlatform_PLATFORM_ANDROID     DevicePlatform = 3
	DevicePlatform_PLATFORM_DESKTOP     DevicePlatform = 4
)

// Enum value maps for DevicePlatform.
var (
	DevicePlatform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_WEB",
		2: "PLATFORM_IOS",
		3: "PLATFORM_ANDROID",
		4: "PLATFORM_DESKTOP",
	}
	DevicePlatform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_WEB":         1,
		"PLATFORM_IOS":         2,
		"PLATFORM_ANDROID":     3,
		"PLATFORM_DESKTOP":     4,
	}
)

func (x DevicePlatform) Enum() *DevicePlatform {
	p := new(DevicePlatform)
	*p = x
	return p
}

func (x DevicePlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DevicePlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (DevicePlatform) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x DevicePlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DevicePlatform.Descriptor instead.
func (DevicePlatform) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENDING     MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_FAILED      MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENDING",
		2: "MESSAGE_STATUS_SENT",
		3: "MESSAGE_STATUS_DELIVERED",
		4: "MESSAGE_STATUS_READ",
		5: "MESSAGE_STATUS_FAILED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENDING":     1,
		"MESSAGE_STATUS_SENT":        2,
		"MESSAGE_STATUS_DELIVERED":   3,
		"MESSAGE_STATUS_READ":        4,
		"MESSAGE_STATUS_FAILED":      5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PagingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagingRequest) Reset() {
	*x = PagingRequest{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagingRequest) ProtoMessage() {}

func (x *PagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagingRequest.ProtoReflect.Descriptor instead.
func (*PagingRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PagingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PagingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PagingRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type UserAvatar struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname        string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar          string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Remark          string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	InfoVersion     int64                  `protobuf:"varint,5,opt,name=info_version,json=infoVersion,proto3" json:"info_version,omitempty"`
	RelationVersion int64                  `protobuf:"varint,6,opt,name=relation_version,json=relationVersion,proto3" json:"relation_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserAvatar) Reset() {
	*x = UserAvatar{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatar) ProtoMessage() {}

func (x *UserAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatar.ProtoReflect.Descriptor instead.
func (*UserAvatar) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserAvatar) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAvatar) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserAvatar) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserAvatar) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserAvatar) GetInfoVersion() int64 {
	if x != nil {
		return x.InfoVersion
	}
	return 0
}

func (x *UserAvatar) GetRelationVersion() int64 {
	if x != nil {
		return x.RelationVersion
	}
	return 0
}

type GroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MetaVersion   int64                  `protobuf:"varint,4,opt,name=meta_version,json=metaVersion,proto3" json:"meta_version,omitempty"`
	OwnerId       int64                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSummary) Reset() {
	*x = GroupSummary{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSummary) ProtoMessage() {}

func (x *GroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSummary.ProtoReflect.Descriptor instead.
func (*GroupSummary) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *GroupSummary) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupSummary) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupSummary) GetMetaVersion() int64 {
	if x != nil {
		return x.MetaVersion
	}
	return 0
}

func (x *GroupSummary) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"gochat.rpc\"W\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"Q\n" +
	"\rPagingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xbf\x01\n" +
	"\n" +
	"UserAvatar\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12!\n" +
	"\finfo_version\x18\x05 \x01(\x03R\vinfoVersion\x12)\n" +
	"\x10relation_version\x18\x06 \x01(\x03R\x0frelationVersion\"\x93\x01\n" +
	"\fGroupSummary\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12!\n" +
	"\fmeta_version\x18\x04 \x01(\x03R\vmetaVersion\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x03R\aownerId*z\n" +
	"\x0eDevicePlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPLATFORM_WEB\x10\x01\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x02\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x03\x12\x14\n" +
	"\x10PLATFORM_DESKTOP\x10\x04*\xb6\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_SENDING\x10\x01\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x02\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x03\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x04\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x05B\x06Z\x04./pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(DevicePlatform)(0),   // 0: gochat.rpc.DevicePlatform
	(MessageStatus)(0),    // 1: gochat.rpc.MessageStatus
	(*BaseResponse)(nil),  // 2: gochat.rpc.BaseResponse
	(*PagingRequest)(nil), // 3: gochat.rpc.PagingRequest
	(*UserAvatar)(nil),    // 4: gochat.rpc.UserAvatar
	(*GroupSummary)(nil),  // 5: gochat.rpc.GroupSummary
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
