// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: group.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIds      []int64                `protobuf:"varint,1,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsByIdsRequest) Reset() {
	*x = GetGroupsByIdsRequest{}
	mi := &file_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsByIdsRequest) ProtoMessage() {}

func (x *GetGroupsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupsByIdsRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type GetGroupsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Groups        []*Group               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsByIdsResponse) Reset() {
	*x = GetGroupsByIdsResponse{}
	mi := &file_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsByIdsResponse) ProtoMessage() {}

func (x *GetGroupsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupsByIdsResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupsByIdsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequestsRequest) Reset() {
	*x = GetGroupRequestsRequest{}
	mi := &file_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequestsRequest) ProtoMessage() {}

func (x *GetGroupRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequestsRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequestsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Requests      []*GroupRequest        `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequestsResponse) Reset() {
	*x = GetGroupRequestsResponse{}
	mi := &file_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequestsResponse) ProtoMessage() {}

func (x *GetGroupRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupRequestsResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupRequestsResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupRequestsResponse) GetRequests() []*GroupRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type HandleGroupRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGroupRequestRequest) Reset() {
	*x = HandleGroupRequestRequest{}
	mi := &file_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGroupRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGroupRequestRequest) ProtoMessage() {}

func (x *HandleGroupRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGroupRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleGroupRequestRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{4}
}

func (x *HandleGroupRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HandleGroupRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type HandleGroupRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGroupRequestResponse) Reset() {
	*x = HandleGroupRequestResponse{}
	mi := &file_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGroupRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGroupRequestResponse) ProtoMessage() {}

func (x *HandleGroupRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGroupRequestResponse.ProtoReflect.Descriptor instead.
func (*HandleGroupRequestResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{5}
}

func (x *HandleGroupRequestResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Nickname      string                 `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{6}
}

func (x *GroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GroupRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GroupRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateGroupNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNicknameRequest) Reset() {
	*x = UpdateGroupNicknameRequest{}
	mi := &file_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNicknameRequest) ProtoMessage() {}

func (x *UpdateGroupNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNicknameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupNicknameRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGroupNicknameRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupNicknameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateGroupNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UpdateGroupNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupNicknameResponse) Reset() {
	*x = UpdateGroupNicknameResponse{}
	mi := &file_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupNicknameResponse) ProtoMessage() {}

func (x *UpdateGroupNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupNicknameResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupNicknameResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupNicknameResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type CheckGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberRequest) Reset() {
	*x = CheckGroupMemberRequest{}
	mi := &file_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberRequest) ProtoMessage() {}

func (x *CheckGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{9}
}

func (x *CheckGroupMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CheckGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGroupMemberResponse) Reset() {
	*x = CheckGroupMemberResponse{}
	mi := &file_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGroupMemberResponse) ProtoMessage() {}

func (x *CheckGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{10}
}

func (x *CheckGroupMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckGroupMemberResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Announcement  string                 `protobuf:"bytes,5,opt,name=announcement,proto3" json:"announcement,omitempty"`
	OwnerId       int64                  `protobuf:"varint,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MetaVersion   int64                  `protobuf:"varint,10,opt,name=meta_version,json=metaVersion,proto3" json:"meta_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{11}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *Group) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Group) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Group) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Group) GetMetaVersion() int64 {
	if x != nil {
		return x.MetaVersion
	}
	return 0
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	InfoVersion   int64                  `protobuf:"varint,6,opt,name=info_version,json=infoVersion,proto3" json:"info_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{12}
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *GroupMember) GetInfoVersion() int64 {
	if x != nil {
		return x.InfoVersion
	}
	return 0
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Group         *Group                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGroupResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupListRequest) Reset() {
	*x = GetGroupListRequest{}
	mi := &file_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListRequest) ProtoMessage() {}

func (x *GetGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupListRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{15}
}

type GetGroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Groups        []*GroupSummary        `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupListResponse) Reset() {
	*x = GetGroupListResponse{}
	mi := &file_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListResponse) ProtoMessage() {}

func (x *GetGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupListResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupListResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupListResponse) GetGroups() []*GroupSummary {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{17}
}

func (x *GetGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Group         *Group                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoResponse) Reset() {
	*x = GetGroupInfoResponse{}
	mi := &file_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResponse) ProtoMessage() {}

func (x *GetGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{18}
}

func (x *GetGroupInfoResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupInfoResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersRequest) Reset() {
	*x = GetGroupMembersRequest{}
	mi := &file_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersRequest) ProtoMessage() {}

func (x *GetGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{19}
}

func (x *GetGroupMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Members       []*GroupMember         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResponse) Reset() {
	*x = GetGroupMembersResponse{}
	mi := &file_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResponse) ProtoMessage() {}

func (x *GetGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{20}
}

func (x *GetGroupMembersResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetGroupMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{21}
}

func (x *JoinGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *JoinGroupRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{22}
}

func (x *JoinGroupResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type QuitGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupRequest) Reset() {
	*x = QuitGroupRequest{}
	mi := &file_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupRequest) ProtoMessage() {}

func (x *QuitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupRequest.ProtoReflect.Descriptor instead.
func (*QuitGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{23}
}

func (x *QuitGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type QuitGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitGroupResponse) Reset() {
	*x = QuitGroupResponse{}
	mi := &file_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitGroupResponse) ProtoMessage() {}

func (x *QuitGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitGroupResponse.ProtoReflect.Descriptor instead.
func (*QuitGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{24}
}

func (x *QuitGroupResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type KickGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickGroupMemberRequest) Reset() {
	*x = KickGroupMemberRequest{}
	mi := &file_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickGroupMemberRequest) ProtoMessage() {}

func (x *KickGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*KickGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{25}
}

func (x *KickGroupMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *KickGroupMemberRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type KickGroupMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickGroupMemberResponse) Reset() {
	*x = KickGroupMemberResponse{}
	mi := &file_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickGroupMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickGroupMemberResponse) ProtoMessage() {}

func (x *KickGroupMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickGroupMemberResponse.ProtoReflect.Descriptor instead.
func (*KickGroupMemberResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{26}
}

func (x *KickGroupMemberResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DismissGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupRequest) Reset() {
	*x = DismissGroupRequest{}
	mi := &file_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupRequest) ProtoMessage() {}

func (x *DismissGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupRequest.ProtoReflect.Descriptor instead.
func (*DismissGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{27}
}

func (x *DismissGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type DismissGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupResponse) Reset() {
	*x = DismissGroupResponse{}
	mi := &file_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupResponse) ProtoMessage() {}

func (x *DismissGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupResponse.ProtoReflect.Descriptor instead.
func (*DismissGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{28}
}

func (x *DismissGroupResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementRequest) Reset() {
	*x = UpdateAnnouncementRequest{}
	mi := &file_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementRequest) ProtoMessage() {}

func (x *UpdateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateAnnouncementRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateAnnouncementRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnouncementResponse) Reset() {
	*x = UpdateAnnouncementResponse{}
	mi := &file_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnouncementResponse) ProtoMessage() {}

func (x *UpdateAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateAnnouncementResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{31}
}

func (x *GetAnnouncementRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Announcement  string                 `protobuf:"bytes,2,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementResponse) Reset() {
	*x = GetAnnouncementResponse{}
	mi := &file_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementResponse) ProtoMessage() {}

func (x *GetAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*GetAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{32}
}

func (x *GetAnnouncementResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetAnnouncementResponse) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

type SearchGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroupsRequest) Reset() {
	*x = SearchGroupsRequest{}
	mi := &file_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroupsRequest) ProtoMessage() {}

func (x *SearchGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroupsRequest.ProtoReflect.Descriptor instead.
func (*SearchGroupsRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{33}
}

func (x *SearchGroupsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Groups        []*GroupSummary        `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGroupsResponse) Reset() {
	*x = SearchGroupsResponse{}
	mi := &file_group_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGroupsResponse) ProtoMessage() {}

func (x *SearchGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGroupsResponse.ProtoReflect.Descriptor instead.
func (*SearchGroupsResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{34}
}

func (x *SearchGroupsResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SearchGroupsResponse) GetGroups() []*GroupSummary {
	if x != nil {
		return x.Groups
	}
	return nil
}

type InviteMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMembersRequest) Reset() {
	*x = InviteMembersRequest{}
	mi := &file_group_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMembersRequest) ProtoMessage() {}

func (x *InviteMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMembersRequest.ProtoReflect.Descriptor instead.
func (*InviteMembersRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{35}
}

func (x *InviteMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *InviteMembersRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type InviteMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMembersResponse) Reset() {
	*x = InviteMembersResponse{}
	mi := &file_group_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMembersResponse) ProtoMessage() {}

func (x *InviteMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMembersResponse.ProtoReflect.Descriptor instead.
func (*InviteMembersResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{36}
}

func (x *InviteMembersResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_group_proto protoreflect.FileDescriptor

const file_group_proto_rawDesc = "" +
	"\n" +
	"\vgroup.proto\x12\n" +
	"gochat.rpc\x1a\fcommon.proto\"4\n" +
	"\x15GetGroupsByIdsRequest\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\x03R\bgroupIds\"q\n" +
	"\x16GetGroupsByIdsResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x12)\n" +
	"\x06groups\x18\x02 \x03(\v2\x11.gochat.rpc.GroupR\x06groups\"4\n" +
	"\x17GetGroupRequestsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"~\n" +
	"\x18GetGroupRequestsResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x124\n" +
	"\brequests\x18\x02 \x03(\v2\x18.gochat.rpc.GroupRequestR\brequests\"R\n" +
	"\x19HandleGroupRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"J\n" +
	"\x1aHandleGroupRequestResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"\xd7\x01\n" +
	"\fGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\"l\n" +
	"\x1aUpdateGroupNicknameRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"K\n" +
	"\x1bUpdateGroupNicknameResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"M\n" +
	"\x17CheckGroupMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"K\n" +
	"\x18CheckGroupMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\"\x9d\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fannouncement\x18\x05 \x01(\tR\fannouncement\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\x03R\aownerId\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12!\n" +
	"\fmeta_version\x18\n" +
	" \x01(\x03R\vmetaVersion\"\xae\x01\n" +
	"\vGroupMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\x12!\n" +
	"\finfo_version\x18\x06 \x01(\x03R\vinfoVersion\"b\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"l\n" +
	"\x13CreateGroupResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x12'\n" +
	"\x05group\x18\x02 \x01(\v2\x11.gochat.rpc.GroupR\x05group\"\x15\n" +
	"\x13GetGroupListRequest\"v\n" +
	"\x14GetGroupListResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x120\n" +
	"\x06groups\x18\x02 \x03(\v2\x18.gochat.rpc.GroupSummaryR\x06groups\"0\n" +
	"\x13GetGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"m\n" +
	"\x14GetGroupInfoResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x12'\n" +
	"\x05group\x18\x02 \x01(\v2\x11.gochat.rpc.GroupR\x05group\"3\n" +
	"\x16GetGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"z\n" +
	"\x17GetGroupMembersResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x121\n" +
	"\amembers\x18\x02 \x03(\v2\x17.gochat.rpc.GroupMemberR\amembers\"G\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x11JoinGroupResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"-\n" +
	"\x10QuitGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"A\n" +
	"\x11QuitGroupResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"P\n" +
	"\x16KickGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\"G\n" +
	"\x17KickGroupMemberResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"0\n" +
	"\x13DismissGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"D\n" +
	"\x14DismissGroupResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"P\n" +
	"\x19UpdateAnnouncementRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"J\n" +
	"\x1aUpdateAnnouncementResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"3\n" +
	"\x16GetAnnouncementRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"k\n" +
	"\x17GetAnnouncementResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x12\"\n" +
	"\fannouncement\x18\x02 \x01(\tR\fannouncement\"/\n" +
	"\x13SearchGroupsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"v\n" +
	"\x14SearchGroupsResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x120\n" +
	"\x06groups\x18\x02 \x03(\v2\x18.gochat.rpc.GroupSummaryR\x06groups\"P\n" +
	"\x14InviteMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\x03R\tmemberIds\"E\n" +
	"\x15InviteMembersResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base2\xf1\v\n" +
	"\fGroupService\x12N\n" +
	"\vCreateGroup\x12\x1e.gochat.rpc.CreateGroupRequest\x1a\x1f.gochat.rpc.CreateGroupResponse\x12Q\n" +
	"\fGetGroupList\x12\x1f.gochat.rpc.GetGroupListRequest\x1a .gochat.rpc.GetGroupListResponse\x12Q\n" +
	"\fGetGroupInfo\x12\x1f.gochat.rpc.GetGroupInfoRequest\x1a .gochat.rpc.GetGroupInfoResponse\x12Z\n" +
	"\x0fGetGroupMembers\x12\".gochat.rpc.GetGroupMembersRequest\x1a#.gochat.rpc.GetGroupMembersResponse\x12H\n" +
	"\tJoinGroup\x12\x1c.gochat.rpc.JoinGroupRequest\x1a\x1d.gochat.rpc.JoinGroupResponse\x12H\n" +
	"\tQuitGroup\x12\x1c.gochat.rpc.QuitGroupRequest\x1a\x1d.gochat.rpc.QuitGroupResponse\x12Z\n" +
	"\x0fKickGroupMember\x12\".gochat.rpc.KickGroupMemberRequest\x1a#.gochat.rpc.KickGroupMemberResponse\x12Q\n" +
	"\fDismissGroup\x12\x1f.gochat.rpc.DismissGroupRequest\x1a .gochat.rpc.DismissGroupResponse\x12c\n" +
	"\x12UpdateAnnouncement\x12%.gochat.rpc.UpdateAnnouncementRequest\x1a&.gochat.rpc.UpdateAnnouncementResponse\x12Z\n" +
	"\x0fGetAnnouncement\x12\".gochat.rpc.GetAnnouncementRequest\x1a#.gochat.rpc.GetAnnouncementResponse\x12Q\n" +
	"\fSearchGroups\x12\x1f.gochat.rpc.SearchGroupsRequest\x1a .gochat.rpc.SearchGroupsResponse\x12T\n" +
	"\rInviteMembers\x12 .gochat.rpc.InviteMembersRequest\x1a!.gochat.rpc.InviteMembersResponse\x12]\n" +
	"\x10CheckGroupMember\x12#.gochat.rpc.CheckGroupMemberRequest\x1a$.gochat.rpc.CheckGroupMemberResponse\x12f\n" +
	"\x13UpdateGroupNickname\x12&.gochat.rpc.UpdateGroupNicknameRequest\x1a'.gochat.rpc.UpdateGroupNicknameResponse\x12]\n" +
	"\x10GetGroupRequests\x12#.gochat.rpc.GetGroupRequestsRequest\x1a$.gochat.rpc.GetGroupRequestsResponse\x12c\n" +
	"\x12HandleGroupRequest\x12%.gochat.rpc.HandleGroupRequestRequest\x1a&.gochat.rpc.HandleGroupRequestResponse\x12W\n" +
	"\x0eGetGroupsByIds\x12!.gochat.rpc.GetGroupsByIdsRequest\x1a\".gochat.rpc.GetGroupsByIdsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_group_proto_rawDescOnce sync.Once
	file_group_proto_rawDescData []byte
)

func file_group_proto_rawDescGZIP() []byte {
	file_group_proto_rawDescOnce.Do(func() {
		file_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)))
	})
	return file_group_proto_rawDescData
}

var file_group_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_group_proto_goTypes = []any{
	(*GetGroupsByIdsRequest)(nil),       // 0: gochat.rpc.GetGroupsByIdsRequest
	(*GetGroupsByIdsResponse)(nil),      // 1: gochat.rpc.GetGroupsByIdsResponse
	(*GetGroupRequestsRequest)(nil),     // 2: gochat.rpc.GetGroupRequestsRequest
	(*GetGroupRequestsResponse)(nil),    // 3: gochat.rpc.GetGroupRequestsResponse
	(*HandleGroupRequestRequest)(nil),   // 4: gochat.rpc.HandleGroupRequestRequest
	(*HandleGroupRequestResponse)(nil),  // 5: gochat.rpc.HandleGroupRequestResponse
	(*GroupRequest)(nil),                // 6: gochat.rpc.GroupRequest
	(*UpdateGroupNicknameRequest)(nil),  // 7: gochat.rpc.UpdateGroupNicknameRequest
	(*UpdateGroupNicknameResponse)(nil), // 8: gochat.rpc.UpdateGroupNicknameResponse
	(*CheckGroupMemberRequest)(nil),     // 9: gochat.rpc.CheckGroupMemberRequest
	(*CheckGroupMemberResponse)(nil),    // 10: gochat.rpc.CheckGroupMemberResponse
	(*Group)(nil),                       // 11: gochat.rpc.Group
	(*GroupMember)(nil),                 // 12: gochat.rpc.GroupMember
	(*CreateGroupRequest)(nil),          // 13: gochat.rpc.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 14: gochat.rpc.CreateGroupResponse
	(*GetGroupListRequest)(nil),         // 15: gochat.rpc.GetGroupListRequest
	(*GetGroupListResponse)(nil),        // 16: gochat.rpc.GetGroupListResponse
	(*GetGroupInfoRequest)(nil),         // 17: gochat.rpc.GetGroupInfoRequest
	(*GetGroupInfoResponse)(nil),        // 18: gochat.rpc.GetGroupInfoResponse
	(*GetGroupMembersRequest)(nil),      // 19: gochat.rpc.GetGroupMembersRequest
	(*GetGroupMembersResponse)(nil),     // 20: gochat.rpc.GetGroupMembersResponse
	(*JoinGroupRequest)(nil),            // 21: gochat.rpc.JoinGroupRequest
	(*JoinGroupResponse)(nil),           // 22: gochat.rpc.JoinGroupResponse
	(*QuitGroupRequest)(nil),            // 23: gochat.rpc.QuitGroupRequest
	(*QuitGroupResponse)(nil),           // 24: gochat.rpc.QuitGroupResponse
	(*KickGroupMemberRequest)(nil),      // 25: gochat.rpc.KickGroupMemberRequest
	(*KickGroupMemberResponse)(nil),     // 26: gochat.rpc.KickGroupMemberResponse
	(*DismissGroupRequest)(nil),         // 27: gochat.rpc.DismissGroupRequest
	(*DismissGroupResponse)(nil),        // 28: gochat.rpc.DismissGroupResponse
	(*UpdateAnnouncementRequest)(nil),   // 29: gochat.rpc.UpdateAnnouncementRequest
	(*UpdateAnnouncementResponse)(nil),  // 30: gochat.rpc.UpdateAnnouncementResponse
	(*GetAnnouncementRequest)(nil),      // 31: gochat.rpc.GetAnnouncementRequest
	(*GetAnnouncementResponse)(nil),     // 32: gochat.rpc.GetAnnouncementResponse
	(*SearchGroupsRequest)(nil),         // 33: gochat.rpc.SearchGroupsRequest
	(*SearchGroupsResponse)(nil),        // 34: gochat.rpc.SearchGroupsResponse
	(*InviteMembersRequest)(nil),        // 35: gochat.rpc.InviteMembersRequest
	(*InviteMembersResponse)(nil),       // 36: gochat.rpc.InviteMembersResponse
	(*BaseResponse)(nil),                // 37: gochat.rpc.BaseResponse
	(*GroupSummary)(nil),                // 38: gochat.rpc.GroupSummary
}
var file_group_proto_depIdxs = []int32{
	37, // 0: gochat.rpc.GetGroupsByIdsResponse.base:type_name -> gochat.rpc.BaseResponse
	11, // 1: gochat.rpc.GetGroupsByIdsResponse.groups:type_name -> gochat.rpc.Group
	37, // 2: gochat.rpc.GetGroupRequestsResponse.base:type_name -> gochat.rpc.BaseResponse
	6,  // 3: gochat.rpc.GetGroupRequestsResponse.requests:type_name -> gochat.rpc.GroupRequest
	37, // 4: gochat.rpc.HandleGroupRequestResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 5: gochat.rpc.UpdateGroupNicknameResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 6: gochat.rpc.CreateGroupResponse.base:type_name -> gochat.rpc.BaseResponse
	11, // 7: gochat.rpc.CreateGroupResponse.group:type_name -> gochat.rpc.Group
	37, // 8: gochat.rpc.GetGroupListResponse.base:type_name -> gochat.rpc.BaseResponse
	38, // 9: gochat.rpc.GetGroupListResponse.groups:type_name -> gochat.rpc.GroupSummary
	37, // 10: gochat.rpc.GetGroupInfoResponse.base:type_name -> gochat.rpc.BaseResponse
	11, // 11: gochat.rpc.GetGroupInfoResponse.group:type_name -> gochat.rpc.Group
	37, // 12: gochat.rpc.GetGroupMembersResponse.base:type_name -> gochat.rpc.BaseResponse
	12, // 13: gochat.rpc.GetGroupMembersResponse.members:type_name -> gochat.rpc.GroupMember
	37, // 14: gochat.rpc.JoinGroupResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 15: gochat.rpc.QuitGroupResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 16: gochat.rpc.KickGroupMemberResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 17: gochat.rpc.DismissGroupResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 18: gochat.rpc.UpdateAnnouncementResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 19: gochat.rpc.GetAnnouncementResponse.base:type_name -> gochat.rpc.BaseResponse
	37, // 20: gochat.rpc.SearchGroupsResponse.base:type_name -> gochat.rpc.BaseResponse
	38, // 21: gochat.rpc.SearchGroupsResponse.groups:type_name -> gochat.rpc.GroupSummary
	37, // 22: gochat.rpc.InviteMembersResponse.base:type_name -> gochat.rpc.BaseResponse
	13, // 23: gochat.rpc.GroupService.CreateGroup:input_type -> gochat.rpc.CreateGroupRequest
	15, // 24: gochat.rpc.GroupService.GetGroupList:input_type -> gochat.rpc.GetGroupListRequest
	17, // 25: gochat.rpc.GroupService.GetGroupInfo:input_type -> gochat.rpc.GetGroupInfoRequest
	19, // 26: gochat.rpc.GroupService.GetGroupMembers:input_type -> gochat.rpc.GetGroupMembersRequest
	21, // 27: gochat.rpc.GroupService.JoinGroup:input_type -> gochat.rpc.JoinGroupRequest
	23, // 28: gochat.rpc.GroupService.QuitGroup:input_type -> gochat.rpc.QuitGroupRequest
	25, // 29: gochat.rpc.GroupService.KickGroupMember:input_type -> gochat.rpc.KickGroupMemberRequest
	27, // 30: gochat.rpc.GroupService.DismissGroup:input_type -> gochat.rpc.DismissGroupRequest
	29, // 31: gochat.rpc.GroupService.UpdateAnnouncement:input_type -> gochat.rpc.UpdateAnnouncementRequest
	31, // 32: gochat.rpc.GroupService.GetAnnouncement:input_type -> gochat.rpc.GetAnnouncementRequest
	33, // 33: gochat.rpc.GroupService.SearchGroups:input_type -> gochat.rpc.SearchGroupsRequest
	35, // 34: gochat.rpc.GroupService.InviteMembers:input_type -> gochat.rpc.InviteMembersRequest
	9,  // 35: gochat.rpc.GroupService.CheckGroupMember:input_type -> gochat.rpc.CheckGroupMemberRequest
	7,  // 36: gochat.rpc.GroupService.UpdateGroupNickname:input_type -> gochat.rpc.UpdateGroupNicknameRequest
	2,  // 37: gochat.rpc.GroupService.GetGroupRequests:input_type -> gochat.rpc.GetGroupRequestsRequest
	4,  // 38: gochat.rpc.GroupService.HandleGroupRequest:input_type -> gochat.rpc.HandleGroupRequestRequest
	0,  // 39: gochat.rpc.GroupService.GetGroupsByIds:input_type -> gochat.rpc.GetGroupsByIdsRequest
	14, // 40: gochat.rpc.GroupService.CreateGroup:output_type -> gochat.rpc.CreateGroupResponse
	16, // 41: gochat.rpc.GroupService.GetGroupList:output_type -> gochat.rpc.GetGroupListResponse
	18, // 42: gochat.rpc.GroupService.GetGroupInfo:output_type -> gochat.rpc.GetGroupInfoResponse
	20, // 43: gochat.rpc.GroupService.GetGroupMembers:output_type -> gochat.rpc.GetGroupMembersResponse
	22, // 44: gochat.rpc.GroupService.JoinGroup:output_type -> gochat.rpc.JoinGroupResponse
	24, // 45: gochat.rpc.GroupService.QuitGroup:output_type -> gochat.rpc.QuitGroupResponse
	26, // 46: gochat.rpc.GroupService.KickGroupMember:output_type -> gochat.rpc.KickGroupMemberResponse
	28, // 47: gochat.rpc.GroupService.DismissGroup:output_type -> gochat.rpc.DismissGroupResponse
	30, // 48: gochat.rpc.GroupService.UpdateAnnouncement:output_type -> gochat.rpc.UpdateAnnouncementResponse
	32, // 49: gochat.rpc.GroupService.GetAnnouncement:output_type -> gochat.rpc.GetAnnouncementResponse
	34, // 50: gochat.rpc.GroupService.SearchGroups:output_type -> gochat.rpc.SearchGroupsResponse
	36, // 51: gochat.rpc.GroupService.InviteMembers:output_type -> gochat.rpc.InviteMembersResponse
	10, // 52: gochat.rpc.GroupService.CheckGroupMember:output_type -> gochat.rpc.CheckGroupMemberResponse
	8,  // 53: gochat.rpc.GroupService.UpdateGroupNickname:output_type -> gochat.rpc.UpdateGroupNicknameResponse
	3,  // 54: gochat.rpc.GroupService.GetGroupRequests:output_type -> gochat.rpc.GetGroupRequestsResponse
	5,  // 55: gochat.rpc.GroupService.HandleGroupRequest:output_type -> gochat.rpc.HandleGroupRequestResponse
	1,  // 56: gochat.rpc.GroupService.GetGroupsByIds:output_type -> gochat.rpc.GetGroupsByIdsResponse
	40, // [40:57] is the sub-list for method output_type
	23, // [23:40] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_group_proto_init() }
func file_group_proto_init() {
	if File_group_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_proto_goTypes,
		DependencyIndexes: file_group_proto_depIdxs,
		MessageInfos:      file_group_proto_msgTypes,
	}.Build()
	File_group_proto = out.File
	file_group_proto_goTypes = nil
	file_group_proto_depIdxs = nil
}
