// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendRequest) Reset() {
	*x = CheckFriendRequest{}
	mi := &file_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendRequest) ProtoMessage() {}

func (x *CheckFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendRequest.ProtoReflect.Descriptor instead.
func (*CheckFriendRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{0}
}

func (x *CheckFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type CheckFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendResponse) Reset() {
	*x = CheckFriendResponse{}
	mi := &file_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendResponse) ProtoMessage() {}

func (x *CheckFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendResponse.ProtoReflect.Descriptor instead.
func (*CheckFriendResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{1}
}

func (x *CheckFriendResponse) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

func (x *CheckFriendResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type FriendApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApply) Reset() {
	*x = FriendApply{}
	mi := &file_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApply) ProtoMessage() {}

func (x *FriendApply) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApply.ProtoReflect.Descriptor instead.
func (*FriendApply) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{2}
}

func (x *FriendApply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendApply) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendApply) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendApply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendApply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendApply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToUserId      int64                  `protobuf:"varint,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ApplyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type HandleApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int64                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleApplyRequest) Reset() {
	*x = HandleApplyRequest{}
	mi := &file_relation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleApplyRequest) ProtoMessage() {}

func (x *HandleApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleApplyRequest.ProtoReflect.Descriptor instead.
func (*HandleApplyRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{5}
}

func (x *HandleApplyRequest) GetApplyId() int64 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *HandleApplyRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type HandleApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleApplyResponse) Reset() {
	*x = HandleApplyResponse{}
	mi := &file_relation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleApplyResponse) ProtoMessage() {}

func (x *HandleApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleApplyResponse.ProtoReflect.Descriptor instead.
func (*HandleApplyResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{6}
}

func (x *HandleApplyResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetFriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	mi := &file_relation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{7}
}

type GetFriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Friends       []*UserAvatar          `protobuf:"bytes,2,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListResponse) Reset() {
	*x = GetFriendListResponse{}
	mi := &file_relation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListResponse) ProtoMessage() {}

func (x *GetFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListResponse.ProtoReflect.Descriptor instead.
func (*GetFriendListResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{8}
}

func (x *GetFriendListResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetFriendListResponse) GetFriends() []*UserAvatar {
	if x != nil {
		return x.Friends
	}
	return nil
}

type GetApplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplyListRequest) Reset() {
	*x = GetApplyListRequest{}
	mi := &file_relation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplyListRequest) ProtoMessage() {}

func (x *GetApplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplyListRequest.ProtoReflect.Descriptor instead.
func (*GetApplyListRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{9}
}

type GetApplyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Applies       []*FriendApply         `protobuf:"bytes,2,rep,name=applies,proto3" json:"applies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplyListResponse) Reset() {
	*x = GetApplyListResponse{}
	mi := &file_relation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplyListResponse) ProtoMessage() {}

func (x *GetApplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplyListResponse.ProtoReflect.Descriptor instead.
func (*GetApplyListResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplyListResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetApplyListResponse) GetApplies() []*FriendApply {
	if x != nil {
		return x.Applies
	}
	return nil
}

type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_relation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_relation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFriendResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type BlockFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFriendRequest) Reset() {
	*x = BlockFriendRequest{}
	mi := &file_relation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFriendRequest) ProtoMessage() {}

func (x *BlockFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFriendRequest.ProtoReflect.Descriptor instead.
func (*BlockFriendRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{13}
}

func (x *BlockFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type BlockFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFriendResponse) Reset() {
	*x = BlockFriendResponse{}
	mi := &file_relation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFriendResponse) ProtoMessage() {}

func (x *BlockFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFriendResponse.ProtoReflect.Descriptor instead.
func (*BlockFriendResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{14}
}

func (x *BlockFriendResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UnblockFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockFriendRequest) Reset() {
	*x = UnblockFriendRequest{}
	mi := &file_relation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockFriendRequest) ProtoMessage() {}

func (x *UnblockFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockFriendRequest.ProtoReflect.Descriptor instead.
func (*UnblockFriendRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{15}
}

func (x *UnblockFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type UnblockFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockFriendResponse) Reset() {
	*x = UnblockFriendResponse{}
	mi := &file_relation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockFriendResponse) ProtoMessage() {}

func (x *UnblockFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockFriendResponse.ProtoReflect.Descriptor instead.
func (*UnblockFriendResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{16}
}

func (x *UnblockFriendResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateRemarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemarkRequest) Reset() {
	*x = UpdateRemarkRequest{}
	mi := &file_relation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemarkRequest) ProtoMessage() {}

func (x *UpdateRemarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemarkRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemarkRequest) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRemarkRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *UpdateRemarkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateRemarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseResponse          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemarkResponse) Reset() {
	*x = UpdateRemarkResponse{}
	mi := &file_relation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemarkResponse) ProtoMessage() {}

func (x *UpdateRemarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemarkResponse.ProtoReflect.Descriptor instead.
func (*UpdateRemarkResponse) Descriptor() ([]byte, []int) {
	return file_relation_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRemarkResponse) GetBase() *BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_relation_proto protoreflect.FileDescriptor

const file_relation_proto_rawDesc = "" +
	"\n" +
	"\x0erelation.proto\x12\n" +
	"gochat.rpc\x1a\fcommon.proto\"J\n" +
	"\x12CheckFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"Q\n" +
	"\x13CheckFriendResponse\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x02 \x01(\bR\tisBlocked\"\xae\x01\n" +
	"\vFriendApply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"F\n" +
	"\fApplyRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\x03R\btoUserId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\rApplyResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"G\n" +
	"\x12HandleApplyRequest\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x03R\aapplyId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"C\n" +
	"\x13HandleApplyResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"\x16\n" +
	"\x14GetFriendListRequest\"w\n" +
	"\x15GetFriendListResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x120\n" +
	"\afriends\x18\x02 \x03(\v2\x16.gochat.rpc.UserAvatarR\afriends\"\x15\n" +
	"\x13GetApplyListRequest\"w\n" +
	"\x14GetApplyListResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\x121\n" +
	"\aapplies\x18\x02 \x03(\v2\x17.gochat.rpc.FriendApplyR\aapplies\"2\n" +
	"\x13DeleteFriendRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\"D\n" +
	"\x14DeleteFriendResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"1\n" +
	"\x12BlockFriendRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\"C\n" +
	"\x13BlockFriendResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"3\n" +
	"\x14UnblockFriendRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\"E\n" +
	"\x15UnblockFriendResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base\"J\n" +
	"\x13UpdateRemarkRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"D\n" +
	"\x14UpdateRemarkResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.gochat.rpc.BaseResponseR\x04base2\xe4\x05\n" +
	"\x0fRelationService\x12<\n" +
	"\x05Apply\x12\x18.gochat.rpc.ApplyRequest\x1a\x19.gochat.rpc.ApplyResponse\x12N\n" +
	"\vHandleApply\x12\x1e.gochat.rpc.HandleApplyRequest\x1a\x1f.gochat.rpc.HandleApplyResponse\x12T\n" +
	"\rGetFriendList\x12 .gochat.rpc.GetFriendListRequest\x1a!.gochat.rpc.GetFriendListResponse\x12Q\n" +
	"\fGetApplyList\x12\x1f.gochat.rpc.GetApplyListRequest\x1a .gochat.rpc.GetApplyListResponse\x12Q\n" +
	"\fDeleteFriend\x12\x1f.gochat.rpc.DeleteFriendRequest\x1a .gochat.rpc.DeleteFriendResponse\x12N\n" +
	"\vBlockFriend\x12\x1e.gochat.rpc.BlockFriendRequest\x1a\x1f.gochat.rpc.BlockFriendResponse\x12T\n" +
	"\rUnblockFriend\x12 .gochat.rpc.UnblockFriendRequest\x1a!.gochat.rpc.UnblockFriendResponse\x12Q\n" +
	"\fUpdateRemark\x12\x1f.gochat.rpc.UpdateRemarkRequest\x1a .gochat.rpc.UpdateRemarkResponse\x12N\n" +
	"\vCheckFriend\x12\x1e.gochat.rpc.CheckFriendRequest\x1a\x1f.gochat.rpc.CheckFriendResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_relation_proto_rawDescOnce sync.Once
	file_relation_proto_rawDescData []byte
)

func file_relation_proto_rawDescGZIP() []byte {
	file_relation_proto_rawDescOnce.Do(func() {
		file_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)))
	})
	return file_relation_proto_rawDescData
}

var file_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_relation_proto_goTypes = []any{
	(*CheckFriendRequest)(nil),    // 0: gochat.rpc.CheckFriendRequest
	(*CheckFriendResponse)(nil),   // 1: gochat.rpc.CheckFriendResponse
	(*FriendApply)(nil),           // 2: gochat.rpc.FriendApply
	(*ApplyRequest)(nil),          // 3: gochat.rpc.ApplyRequest
	(*ApplyResponse)(nil),         // 4: gochat.rpc.ApplyResponse
	(*HandleApplyRequest)(nil),    // 5: gochat.rpc.HandleApplyRequest
	(*HandleApplyResponse)(nil),   // 6: gochat.rpc.HandleApplyResponse
	(*GetFriendListRequest)(nil),  // 7: gochat.rpc.GetFriendListRequest
	(*GetFriendListResponse)(nil), // 8: gochat.rpc.GetFriendListResponse
	(*GetApplyListRequest)(nil),   // 9: gochat.rpc.GetApplyListRequest
	(*GetApplyListResponse)(nil),  // 10: gochat.rpc.GetApplyListResponse
	(*DeleteFriendRequest)(nil),   // 11: gochat.rpc.DeleteFriendRequest
	(*DeleteFriendResponse)(nil),  // 12: gochat.rpc.DeleteFriendResponse
	(*BlockFriendRequest)(nil),    // 13: gochat.rpc.BlockFriendRequest
	(*BlockFriendResponse)(nil),   // 14: gochat.rpc.BlockFriendResponse
	(*UnblockFriendRequest)(nil),  // 15: gochat.rpc.UnblockFriendRequest
	(*UnblockFriendResponse)(nil), // 16: gochat.rpc.UnblockFriendResponse
	(*UpdateRemarkRequest)(nil),   // 17: gochat.rpc.UpdateRemarkRequest
	(*UpdateRemarkResponse)(nil),  // 18: gochat.rpc.UpdateRemarkResponse
	(*BaseResponse)(nil),          // 19: gochat.rpc.BaseResponse
	(*UserAvatar)(nil),            // 20: gochat.rpc.UserAvatar
}
var file_relation_proto_depIdxs = []int32{
	19, // 0: gochat.rpc.ApplyResponse.base:type_name -> gochat.rpc.BaseResponse
	19, // 1: gochat.rpc.HandleApplyResponse.base:type_name -> gochat.rpc.BaseResponse
	19, // 2: gochat.rpc.GetFriendListResponse.base:type_name -> gochat.rpc.BaseResponse
	20, // 3: gochat.rpc.GetFriendListResponse.friends:type_name -> gochat.rpc.UserAvatar
	19, // 4: gochat.rpc.GetApplyListResponse.base:type_name -> gochat.rpc.BaseResponse
	2,  // 5: gochat.rpc.GetApplyListResponse.applies:type_name -> gochat.rpc.FriendApply
	19, // 6: gochat.rpc.DeleteFriendResponse.base:type_name -> gochat.rpc.BaseResponse
	19, // 7: gochat.rpc.BlockFriendResponse.base:type_name -> gochat.rpc.BaseResponse
	19, // 8: gochat.rpc.UnblockFriendResponse.base:type_name -> gochat.rpc.BaseResponse
	19, // 9: gochat.rpc.UpdateRemarkResponse.base:type_name -> gochat.rpc.BaseResponse
	3,  // 10: gochat.rpc.RelationService.Apply:input_type -> gochat.rpc.ApplyRequest
	5,  // 11: gochat.rpc.RelationService.HandleApply:input_type -> gochat.rpc.HandleApplyRequest
	7,  // 12: gochat.rpc.RelationService.GetFriendList:input_type -> gochat.rpc.GetFriendListRequest
	9,  // 13: gochat.rpc.RelationService.GetApplyList:input_type -> gochat.rpc.GetApplyListRequest
	11, // 14: gochat.rpc.RelationService.DeleteFriend:input_type -> gochat.rpc.DeleteFriendRequest
	13, // 15: gochat.rpc.RelationService.BlockFriend:input_type -> gochat.rpc.BlockFriendRequest
	15, // 16: gochat.rpc.RelationService.UnblockFriend:input_type -> gochat.rpc.UnblockFriendRequest
	17, // 17: gochat.rpc.RelationService.UpdateRemark:input_type -> gochat.rpc.UpdateRemarkRequest
	0,  // 18: gochat.rpc.RelationService.CheckFriend:input_type -> gochat.rpc.CheckFriendRequest
	4,  // 19: gochat.rpc.RelationService.Apply:output_type -> gochat.rpc.ApplyResponse
	6,  // 20: gochat.rpc.RelationService.HandleApply:output_type -> gochat.rpc.HandleApplyResponse
	8,  // 21: gochat.rpc.RelationService.GetFriendList:output_type -> gochat.rpc.GetFriendListResponse
	10, // 22: gochat.rpc.RelationService.GetApplyList:output_type -> gochat.rpc.GetApplyListResponse
	12, // 23: gochat.rpc.RelationService.DeleteFriend:output_type -> gochat.rpc.DeleteFriendResponse
	14, // 24: gochat.rpc.RelationService.BlockFriend:output_type -> gochat.rpc.BlockFriendResponse
	16, // 25: gochat.rpc.RelationService.UnblockFriend:output_type -> gochat.rpc.UnblockFriendResponse
	18, // 26: gochat.rpc.RelationService.UpdateRemark:output_type -> gochat.rpc.UpdateRemarkResponse
	1,  // 27: gochat.rpc.RelationService.CheckFriend:output_type -> gochat.rpc.CheckFriendResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_relation_proto_init() }
func file_relation_proto_init() {
	if File_relation_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_proto_rawDesc), len(file_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_proto_goTypes,
		DependencyIndexes: file_relation_proto_depIdxs,
		MessageInfos:      file_relation_proto_msgTypes,
	}.Build()
	File_relation_proto = out.File
	file_relation_proto_goTypes = nil
	file_relation_proto_depIdxs = nil
}
